package com.github.rviehmann.aoc2021;

import static java.lang.Long.parseLong;

public class Day02 {

    // From: https://adventofcode.com/2021/day/2/input
    private static final String INPUT =
            "forward 2\n" +
                    "forward 6\n" +
                    "forward 8\n" +
                    "forward 7\n" +
                    "down 5\n" +
                    "forward 8\n" +
                    "forward 9\n" +
                    "down 2\n" +
                    "forward 6\n" +
                    "down 9\n" +
                    "forward 1\n" +
                    "forward 8\n" +
                    "forward 6\n" +
                    "forward 7\n" +
                    "down 4\n" +
                    "down 5\n" +
                    "forward 1\n" +
                    "up 5\n" +
                    "down 7\n" +
                    "down 7\n" +
                    "down 1\n" +
                    "up 2\n" +
                    "forward 3\n" +
                    "forward 2\n" +
                    "forward 2\n" +
                    "forward 5\n" +
                    "up 5\n" +
                    "forward 4\n" +
                    "forward 9\n" +
                    "forward 6\n" +
                    "down 4\n" +
                    "down 9\n" +
                    "down 2\n" +
                    "up 6\n" +
                    "forward 9\n" +
                    "up 7\n" +
                    "forward 7\n" +
                    "forward 5\n" +
                    "up 3\n" +
                    "forward 4\n" +
                    "forward 9\n" +
                    "up 5\n" +
                    "down 3\n" +
                    "up 6\n" +
                    "down 5\n" +
                    "down 4\n" +
                    "up 6\n" +
                    "forward 9\n" +
                    "forward 6\n" +
                    "down 9\n" +
                    "up 3\n" +
                    "down 7\n" +
                    "up 1\n" +
                    "forward 8\n" +
                    "forward 3\n" +
                    "forward 8\n" +
                    "up 6\n" +
                    "forward 7\n" +
                    "forward 5\n" +
                    "forward 8\n" +
                    "up 2\n" +
                    "forward 2\n" +
                    "forward 7\n" +
                    "forward 7\n" +
                    "down 1\n" +
                    "forward 7\n" +
                    "up 7\n" +
                    "down 3\n" +
                    "forward 9\n" +
                    "down 5\n" +
                    "down 2\n" +
                    "forward 5\n" +
                    "forward 1\n" +
                    "forward 4\n" +
                    "forward 6\n" +
                    "up 2\n" +
                    "up 7\n" +
                    "forward 2\n" +
                    "forward 6\n" +
                    "forward 7\n" +
                    "down 9\n" +
                    "up 8\n" +
                    "down 9\n" +
                    "down 3\n" +
                    "up 8\n" +
                    "down 3\n" +
                    "down 2\n" +
                    "up 6\n" +
                    "forward 3\n" +
                    "forward 9\n" +
                    "down 4\n" +
                    "forward 5\n" +
                    "down 6\n" +
                    "up 8\n" +
                    "forward 1\n" +
                    "down 6\n" +
                    "down 6\n" +
                    "forward 5\n" +
                    "down 6\n" +
                    "forward 8\n" +
                    "up 7\n" +
                    "down 3\n" +
                    "forward 7\n" +
                    "forward 3\n" +
                    "forward 1\n" +
                    "forward 4\n" +
                    "forward 4\n" +
                    "down 3\n" +
                    "up 9\n" +
                    "up 5\n" +
                    "forward 1\n" +
                    "down 2\n" +
                    "up 4\n" +
                    "forward 7\n" +
                    "up 4\n" +
                    "down 3\n" +
                    "down 5\n" +
                    "down 8\n" +
                    "forward 4\n" +
                    "up 8\n" +
                    "forward 7\n" +
                    "up 3\n" +
                    "up 4\n" +
                    "up 9\n" +
                    "forward 1\n" +
                    "forward 1\n" +
                    "down 6\n" +
                    "forward 1\n" +
                    "down 8\n" +
                    "up 4\n" +
                    "forward 9\n" +
                    "forward 9\n" +
                    "down 6\n" +
                    "forward 9\n" +
                    "forward 8\n" +
                    "down 2\n" +
                    "up 3\n" +
                    "up 3\n" +
                    "down 9\n" +
                    "forward 7\n" +
                    "forward 8\n" +
                    "down 4\n" +
                    "forward 1\n" +
                    "up 3\n" +
                    "forward 3\n" +
                    "down 3\n" +
                    "down 9\n" +
                    "down 5\n" +
                    "up 7\n" +
                    "up 2\n" +
                    "forward 7\n" +
                    "forward 2\n" +
                    "forward 5\n" +
                    "forward 4\n" +
                    "down 7\n" +
                    "forward 7\n" +
                    "up 1\n" +
                    "up 3\n" +
                    "down 6\n" +
                    "down 4\n" +
                    "forward 9\n" +
                    "forward 8\n" +
                    "down 5\n" +
                    "down 4\n" +
                    "down 1\n" +
                    "down 5\n" +
                    "forward 9\n" +
                    "forward 8\n" +
                    "down 3\n" +
                    "forward 5\n" +
                    "forward 3\n" +
                    "forward 6\n" +
                    "down 6\n" +
                    "forward 3\n" +
                    "up 9\n" +
                    "forward 4\n" +
                    "down 7\n" +
                    "forward 3\n" +
                    "forward 7\n" +
                    "forward 1\n" +
                    "forward 5\n" +
                    "down 1\n" +
                    "forward 1\n" +
                    "down 6\n" +
                    "up 7\n" +
                    "down 3\n" +
                    "forward 2\n" +
                    "down 4\n" +
                    "forward 6\n" +
                    "up 6\n" +
                    "forward 8\n" +
                    "forward 8\n" +
                    "down 5\n" +
                    "up 4\n" +
                    "forward 7\n" +
                    "forward 6\n" +
                    "up 4\n" +
                    "forward 6\n" +
                    "down 1\n" +
                    "forward 6\n" +
                    "forward 2\n" +
                    "up 4\n" +
                    "down 6\n" +
                    "down 7\n" +
                    "forward 4\n" +
                    "down 4\n" +
                    "forward 1\n" +
                    "down 3\n" +
                    "forward 5\n" +
                    "forward 5\n" +
                    "forward 9\n" +
                    "forward 3\n" +
                    "up 7\n" +
                    "down 7\n" +
                    "forward 7\n" +
                    "forward 5\n" +
                    "down 1\n" +
                    "down 1\n" +
                    "forward 3\n" +
                    "down 8\n" +
                    "forward 1\n" +
                    "forward 2\n" +
                    "forward 9\n" +
                    "forward 1\n" +
                    "forward 3\n" +
                    "down 3\n" +
                    "up 4\n" +
                    "forward 5\n" +
                    "down 1\n" +
                    "forward 3\n" +
                    "up 7\n" +
                    "forward 3\n" +
                    "forward 6\n" +
                    "up 6\n" +
                    "up 3\n" +
                    "forward 9\n" +
                    "forward 5\n" +
                    "down 2\n" +
                    "up 4\n" +
                    "up 3\n" +
                    "forward 3\n" +
                    "forward 7\n" +
                    "down 1\n" +
                    "forward 5\n" +
                    "forward 5\n" +
                    "down 1\n" +
                    "forward 4\n" +
                    "forward 2\n" +
                    "down 1\n" +
                    "down 9\n" +
                    "down 7\n" +
                    "up 1\n" +
                    "forward 2\n" +
                    "down 2\n" +
                    "forward 3\n" +
                    "forward 8\n" +
                    "forward 4\n" +
                    "forward 6\n" +
                    "down 4\n" +
                    "down 1\n" +
                    "forward 5\n" +
                    "forward 1\n" +
                    "forward 7\n" +
                    "down 8\n" +
                    "forward 9\n" +
                    "down 6\n" +
                    "forward 3\n" +
                    "up 5\n" +
                    "up 1\n" +
                    "up 7\n" +
                    "down 5\n" +
                    "forward 7\n" +
                    "forward 5\n" +
                    "forward 5\n" +
                    "up 1\n" +
                    "forward 8\n" +
                    "down 8\n" +
                    "down 7\n" +
                    "forward 9\n" +
                    "forward 9\n" +
                    "down 3\n" +
                    "forward 7\n" +
                    "forward 2\n" +
                    "down 1\n" +
                    "down 6\n" +
                    "down 1\n" +
                    "forward 7\n" +
                    "down 3\n" +
                    "forward 1\n" +
                    "forward 1\n" +
                    "forward 6\n" +
                    "forward 6\n" +
                    "up 9\n" +
                    "down 3\n" +
                    "forward 9\n" +
                    "down 8\n" +
                    "forward 4\n" +
                    "up 6\n" +
                    "down 4\n" +
                    "down 7\n" +
                    "forward 5\n" +
                    "up 3\n" +
                    "forward 1\n" +
                    "forward 8\n" +
                    "up 6\n" +
                    "up 3\n" +
                    "down 2\n" +
                    "forward 2\n" +
                    "forward 5\n" +
                    "forward 1\n" +
                    "down 8\n" +
                    "down 8\n" +
                    "down 3\n" +
                    "forward 5\n" +
                    "forward 4\n" +
                    "forward 4\n" +
                    "forward 5\n" +
                    "up 5\n" +
                    "forward 2\n" +
                    "forward 5\n" +
                    "up 5\n" +
                    "forward 6\n" +
                    "forward 6\n" +
                    "forward 9\n" +
                    "up 5\n" +
                    "forward 4\n" +
                    "up 4\n" +
                    "forward 8\n" +
                    "down 8\n" +
                    "forward 5\n" +
                    "forward 2\n" +
                    "forward 4\n" +
                    "forward 3\n" +
                    "forward 1\n" +
                    "down 1\n" +
                    "down 9\n" +
                    "down 2\n" +
                    "forward 4\n" +
                    "down 3\n" +
                    "down 6\n" +
                    "forward 2\n" +
                    "up 7\n" +
                    "forward 6\n" +
                    "down 4\n" +
                    "up 9\n" +
                    "down 1\n" +
                    "forward 8\n" +
                    "forward 1\n" +
                    "forward 1\n" +
                    "down 9\n" +
                    "down 3\n" +
                    "down 2\n" +
                    "down 7\n" +
                    "up 5\n" +
                    "down 7\n" +
                    "up 9\n" +
                    "down 8\n" +
                    "down 7\n" +
                    "forward 9\n" +
                    "forward 7\n" +
                    "up 4\n" +
                    "forward 5\n" +
                    "up 9\n" +
                    "down 4\n" +
                    "forward 1\n" +
                    "forward 9\n" +
                    "down 7\n" +
                    "up 9\n" +
                    "forward 6\n" +
                    "forward 4\n" +
                    "up 8\n" +
                    "down 2\n" +
                    "forward 1\n" +
                    "up 6\n" +
                    "up 5\n" +
                    "down 4\n" +
                    "forward 8\n" +
                    "down 3\n" +
                    "down 5\n" +
                    "down 6\n" +
                    "up 1\n" +
                    "up 9\n" +
                    "up 7\n" +
                    "up 5\n" +
                    "forward 1\n" +
                    "forward 3\n" +
                    "down 7\n" +
                    "forward 9\n" +
                    "forward 2\n" +
                    "forward 6\n" +
                    "down 4\n" +
                    "down 7\n" +
                    "forward 3\n" +
                    "down 1\n" +
                    "up 5\n" +
                    "forward 3\n" +
                    "down 3\n" +
                    "down 1\n" +
                    "forward 1\n" +
                    "forward 4\n" +
                    "forward 8\n" +
                    "down 4\n" +
                    "down 1\n" +
                    "forward 3\n" +
                    "down 7\n" +
                    "up 9\n" +
                    "down 8\n" +
                    "down 1\n" +
                    "forward 2\n" +
                    "down 6\n" +
                    "down 9\n" +
                    "down 9\n" +
                    "forward 2\n" +
                    "forward 8\n" +
                    "up 2\n" +
                    "down 5\n" +
                    "down 9\n" +
                    "forward 1\n" +
                    "up 9\n" +
                    "down 7\n" +
                    "forward 8\n" +
                    "down 7\n" +
                    "up 4\n" +
                    "forward 8\n" +
                    "down 8\n" +
                    "down 7\n" +
                    "forward 6\n" +
                    "up 7\n" +
                    "down 4\n" +
                    "down 9\n" +
                    "forward 9\n" +
                    "up 8\n" +
                    "down 8\n" +
                    "down 8\n" +
                    "down 8\n" +
                    "down 5\n" +
                    "forward 2\n" +
                    "up 9\n" +
                    "down 2\n" +
                    "up 7\n" +
                    "down 7\n" +
                    "down 3\n" +
                    "down 6\n" +
                    "forward 9\n" +
                    "forward 1\n" +
                    "down 1\n" +
                    "down 5\n" +
                    "up 4\n" +
                    "down 5\n" +
                    "forward 5\n" +
                    "up 2\n" +
                    "forward 5\n" +
                    "down 5\n" +
                    "forward 1\n" +
                    "forward 9\n" +
                    "down 9\n" +
                    "forward 3\n" +
                    "forward 3\n" +
                    "down 8\n" +
                    "down 2\n" +
                    "down 8\n" +
                    "forward 8\n" +
                    "forward 7\n" +
                    "up 6\n" +
                    "down 4\n" +
                    "down 5\n" +
                    "forward 8\n" +
                    "forward 4\n" +
                    "forward 7\n" +
                    "forward 1\n" +
                    "down 9\n" +
                    "down 4\n" +
                    "down 2\n" +
                    "forward 5\n" +
                    "down 3\n" +
                    "down 7\n" +
                    "down 5\n" +
                    "forward 8\n" +
                    "up 1\n" +
                    "down 4\n" +
                    "down 7\n" +
                    "down 7\n" +
                    "forward 2\n" +
                    "up 5\n" +
                    "forward 5\n" +
                    "up 2\n" +
                    "up 4\n" +
                    "down 9\n" +
                    "forward 7\n" +
                    "forward 6\n" +
                    "forward 6\n" +
                    "down 2\n" +
                    "forward 7\n" +
                    "forward 7\n" +
                    "down 7\n" +
                    "forward 8\n" +
                    "down 2\n" +
                    "up 9\n" +
                    "down 1\n" +
                    "forward 9\n" +
                    "down 9\n" +
                    "forward 3\n" +
                    "down 9\n" +
                    "down 2\n" +
                    "forward 9\n" +
                    "forward 8\n" +
                    "down 7\n" +
                    "up 2\n" +
                    "forward 8\n" +
                    "forward 1\n" +
                    "up 2\n" +
                    "down 7\n" +
                    "up 7\n" +
                    "down 8\n" +
                    "up 1\n" +
                    "up 4\n" +
                    "up 2\n" +
                    "up 3\n" +
                    "down 7\n" +
                    "forward 1\n" +
                    "down 8\n" +
                    "down 4\n" +
                    "down 2\n" +
                    "down 4\n" +
                    "up 8\n" +
                    "forward 8\n" +
                    "down 2\n" +
                    "up 5\n" +
                    "up 4\n" +
                    "forward 7\n" +
                    "up 1\n" +
                    "forward 3\n" +
                    "down 8\n" +
                    "down 4\n" +
                    "forward 4\n" +
                    "down 8\n" +
                    "forward 2\n" +
                    "down 1\n" +
                    "up 9\n" +
                    "forward 9\n" +
                    "down 4\n" +
                    "up 2\n" +
                    "down 8\n" +
                    "up 9\n" +
                    "forward 6\n" +
                    "down 7\n" +
                    "up 7\n" +
                    "forward 9\n" +
                    "forward 1\n" +
                    "down 8\n" +
                    "forward 5\n" +
                    "down 9\n" +
                    "forward 6\n" +
                    "down 9\n" +
                    "forward 9\n" +
                    "forward 1\n" +
                    "down 8\n" +
                    "up 4\n" +
                    "forward 9\n" +
                    "forward 3\n" +
                    "down 9\n" +
                    "up 8\n" +
                    "forward 4\n" +
                    "up 8\n" +
                    "forward 7\n" +
                    "down 7\n" +
                    "up 6\n" +
                    "down 7\n" +
                    "down 2\n" +
                    "down 7\n" +
                    "forward 3\n" +
                    "forward 2\n" +
                    "down 6\n" +
                    "down 2\n" +
                    "down 7\n" +
                    "up 4\n" +
                    "forward 5\n" +
                    "down 5\n" +
                    "forward 2\n" +
                    "up 3\n" +
                    "up 8\n" +
                    "forward 8\n" +
                    "forward 1\n" +
                    "forward 7\n" +
                    "down 7\n" +
                    "down 2\n" +
                    "forward 1\n" +
                    "down 7\n" +
                    "down 7\n" +
                    "up 2\n" +
                    "up 7\n" +
                    "up 7\n" +
                    "forward 4\n" +
                    "down 5\n" +
                    "forward 5\n" +
                    "forward 7\n" +
                    "forward 7\n" +
                    "down 7\n" +
                    "down 8\n" +
                    "forward 8\n" +
                    "forward 8\n" +
                    "up 3\n" +
                    "up 9\n" +
                    "forward 2\n" +
                    "down 7\n" +
                    "up 3\n" +
                    "up 1\n" +
                    "up 1\n" +
                    "down 9\n" +
                    "up 5\n" +
                    "down 6\n" +
                    "up 8\n" +
                    "up 3\n" +
                    "up 5\n" +
                    "forward 7\n" +
                    "forward 3\n" +
                    "forward 8\n" +
                    "forward 4\n" +
                    "up 1\n" +
                    "forward 2\n" +
                    "forward 1\n" +
                    "up 5\n" +
                    "forward 9\n" +
                    "forward 8\n" +
                    "down 7\n" +
                    "up 1\n" +
                    "forward 7\n" +
                    "down 8\n" +
                    "forward 1\n" +
                    "forward 9\n" +
                    "forward 9\n" +
                    "forward 9\n" +
                    "forward 8\n" +
                    "down 1\n" +
                    "forward 8\n" +
                    "forward 7\n" +
                    "up 9\n" +
                    "up 3\n" +
                    "forward 8\n" +
                    "forward 2\n" +
                    "up 2\n" +
                    "down 7\n" +
                    "down 6\n" +
                    "forward 4\n" +
                    "forward 3\n" +
                    "forward 6\n" +
                    "up 7\n" +
                    "down 9\n" +
                    "forward 1\n" +
                    "forward 4\n" +
                    "down 1\n" +
                    "forward 4\n" +
                    "up 3\n" +
                    "down 8\n" +
                    "forward 1\n" +
                    "up 6\n" +
                    "forward 8\n" +
                    "forward 2\n" +
                    "forward 1\n" +
                    "forward 8\n" +
                    "forward 4\n" +
                    "down 7\n" +
                    "forward 4\n" +
                    "forward 6\n" +
                    "down 2\n" +
                    "up 4\n" +
                    "forward 4\n" +
                    "forward 3\n" +
                    "down 5\n" +
                    "forward 8\n" +
                    "forward 4\n" +
                    "forward 5\n" +
                    "forward 7\n" +
                    "forward 6\n" +
                    "forward 5\n" +
                    "forward 9\n" +
                    "down 4\n" +
                    "down 9\n" +
                    "forward 6\n" +
                    "up 7\n" +
                    "down 6\n" +
                    "down 3\n" +
                    "down 2\n" +
                    "up 9\n" +
                    "forward 7\n" +
                    "down 4\n" +
                    "down 5\n" +
                    "forward 2\n" +
                    "forward 3\n" +
                    "forward 2\n" +
                    "forward 9\n" +
                    "forward 7\n" +
                    "forward 8\n" +
                    "down 9\n" +
                    "down 7\n" +
                    "down 9\n" +
                    "down 7\n" +
                    "forward 5\n" +
                    "forward 2\n" +
                    "down 5\n" +
                    "forward 6\n" +
                    "down 1\n" +
                    "down 2\n" +
                    "down 6\n" +
                    "forward 9\n" +
                    "down 3\n" +
                    "up 6\n" +
                    "down 4\n" +
                    "down 5\n" +
                    "forward 3\n" +
                    "forward 7\n" +
                    "down 8\n" +
                    "forward 2\n" +
                    "forward 5\n" +
                    "down 9\n" +
                    "down 3\n" +
                    "up 5\n" +
                    "down 6\n" +
                    "forward 6\n" +
                    "up 3\n" +
                    "down 6\n" +
                    "down 1\n" +
                    "down 8\n" +
                    "down 5\n" +
                    "down 3\n" +
                    "forward 3\n" +
                    "up 6\n" +
                    "up 7\n" +
                    "forward 8\n" +
                    "forward 9\n" +
                    "forward 2\n" +
                    "forward 6\n" +
                    "forward 2\n" +
                    "forward 3\n" +
                    "down 7\n" +
                    "down 3\n" +
                    "down 3\n" +
                    "down 6\n" +
                    "down 2\n" +
                    "forward 4\n" +
                    "forward 3\n" +
                    "forward 8\n" +
                    "up 1\n" +
                    "down 9\n" +
                    "forward 5\n" +
                    "up 3\n" +
                    "down 7\n" +
                    "down 6\n" +
                    "forward 8\n" +
                    "forward 1\n" +
                    "up 6\n" +
                    "forward 3\n" +
                    "forward 1\n" +
                    "up 9\n" +
                    "forward 6\n" +
                    "forward 3\n" +
                    "down 9\n" +
                    "down 4\n" +
                    "down 9\n" +
                    "forward 5\n" +
                    "down 8\n" +
                    "down 3\n" +
                    "forward 1\n" +
                    "forward 1\n" +
                    "down 9\n" +
                    "down 6\n" +
                    "down 3\n" +
                    "up 7\n" +
                    "down 3\n" +
                    "forward 5\n" +
                    "down 2\n" +
                    "forward 7\n" +
                    "forward 2\n" +
                    "forward 5\n" +
                    "up 7\n" +
                    "forward 4\n" +
                    "forward 4\n" +
                    "up 3\n" +
                    "down 6\n" +
                    "down 7\n" +
                    "up 1\n" +
                    "down 6\n" +
                    "forward 1\n" +
                    "forward 9\n" +
                    "down 7\n" +
                    "down 8\n" +
                    "forward 5\n" +
                    "down 1\n" +
                    "down 9\n" +
                    "up 5\n" +
                    "up 4\n" +
                    "up 3\n" +
                    "forward 6\n" +
                    "down 6\n" +
                    "forward 4\n" +
                    "forward 8\n" +
                    "up 6\n" +
                    "up 2\n" +
                    "down 9\n" +
                    "forward 2\n" +
                    "forward 5\n" +
                    "forward 1\n" +
                    "forward 3\n" +
                    "forward 9\n" +
                    "up 3\n" +
                    "forward 2\n" +
                    "forward 1\n" +
                    "forward 3\n" +
                    "forward 3\n" +
                    "up 9\n" +
                    "forward 3\n" +
                    "forward 7\n" +
                    "down 6\n" +
                    "forward 2\n" +
                    "down 8\n" +
                    "up 9\n" +
                    "forward 8\n" +
                    "forward 5\n" +
                    "forward 2\n" +
                    "up 8\n" +
                    "down 9\n" +
                    "up 5\n" +
                    "forward 3\n" +
                    "down 4\n" +
                    "forward 1\n" +
                    "up 9\n" +
                    "down 4\n" +
                    "down 5\n" +
                    "up 4\n" +
                    "down 6\n" +
                    "down 4\n" +
                    "down 6\n" +
                    "down 4\n" +
                    "forward 4\n" +
                    "down 2\n" +
                    "down 1\n" +
                    "down 6\n" +
                    "forward 2\n" +
                    "down 1\n" +
                    "down 3\n" +
                    "forward 4\n" +
                    "down 3\n" +
                    "down 5\n" +
                    "down 5\n" +
                    "up 1\n" +
                    "up 4\n" +
                    "down 4\n" +
                    "down 4\n" +
                    "down 5\n" +
                    "down 4\n" +
                    "down 5\n" +
                    "forward 5\n" +
                    "down 8\n" +
                    "down 5\n" +
                    "down 5\n" +
                    "down 9\n" +
                    "up 1\n" +
                    "up 5\n" +
                    "forward 5\n" +
                    "down 1\n" +
                    "down 9\n" +
                    "down 4\n" +
                    "down 3\n" +
                    "forward 3\n" +
                    "down 2\n" +
                    "forward 9\n" +
                    "down 3\n" +
                    "forward 1\n" +
                    "down 9\n" +
                    "down 5\n" +
                    "up 7\n" +
                    "forward 3\n" +
                    "forward 1\n" +
                    "forward 2\n" +
                    "down 5\n" +
                    "forward 8\n" +
                    "down 3\n" +
                    "down 3\n" +
                    "forward 6\n" +
                    "down 8\n" +
                    "down 3\n" +
                    "down 8\n" +
                    "up 9\n" +
                    "forward 3\n" +
                    "down 6\n" +
                    "forward 4\n" +
                    "down 6\n" +
                    "down 4\n" +
                    "up 5\n" +
                    "forward 1\n" +
                    "up 6\n" +
                    "up 2\n" +
                    "forward 2\n" +
                    "down 8\n" +
                    "forward 7\n" +
                    "forward 8\n" +
                    "down 6\n" +
                    "down 7\n" +
                    "forward 7\n" +
                    "up 3\n" +
                    "forward 3\n" +
                    "up 6\n" +
                    "forward 3\n" +
                    "down 1\n" +
                    "down 7\n" +
                    "forward 9\n" +
                    "forward 5\n" +
                    "up 1\n" +
                    "forward 7\n" +
                    "forward 1\n" +
                    "down 3\n" +
                    "forward 1\n" +
                    "up 4\n" +
                    "up 2\n" +
                    "up 1\n" +
                    "down 8\n" +
                    "forward 9\n" +
                    "forward 3\n" +
                    "forward 4\n" +
                    "up 7\n" +
                    "forward 5\n" +
                    "down 1\n" +
                    "down 8\n" +
                    "down 3\n" +
                    "down 4\n" +
                    "down 6\n" +
                    "down 5\n" +
                    "forward 4\n" +
                    "down 4\n" +
                    "down 2\n" +
                    "down 4\n" +
                    "down 3\n" +
                    "down 3\n" +
                    "forward 4\n" +
                    "up 3\n" +
                    "forward 6\n" +
                    "down 7\n" +
                    "forward 4\n" +
                    "up 2\n" +
                    "down 7\n" +
                    "forward 8\n" +
                    "up 9\n" +
                    "forward 6\n" +
                    "forward 8\n" +
                    "down 1\n" +
                    "down 6\n" +
                    "forward 6\n" +
                    "down 6\n" +
                    "down 9\n" +
                    "up 8\n" +
                    "forward 8\n" +
                    "up 5\n" +
                    "forward 6\n" +
                    "forward 9\n" +
                    "forward 4\n" +
                    "up 2\n" +
                    "forward 3\n" +
                    "down 7\n" +
                    "down 8\n" +
                    "down 4\n" +
                    "up 8\n" +
                    "forward 8\n" +
                    "forward 1\n" +
                    "up 5\n" +
                    "up 4\n" +
                    "up 1\n" +
                    "down 9\n" +
                    "down 9\n" +
                    "up 2\n" +
                    "forward 9\n" +
                    "down 7\n" +
                    "down 2\n" +
                    "up 2\n" +
                    "down 1\n" +
                    "forward 6\n" +
                    "forward 2\n" +
                    "down 5\n" +
                    "down 8\n" +
                    "forward 6\n" +
                    "down 2\n" +
                    "down 3\n" +
                    "forward 6\n" +
                    "forward 7\n" +
                    "up 8\n" +
                    "down 4\n" +
                    "forward 5\n" +
                    "down 9\n" +
                    "down 2\n" +
                    "down 7\n" +
                    "down 9\n" +
                    "down 5\n" +
                    "forward 9\n" +
                    "forward 2\n" +
                    "down 6\n" +
                    "forward 7\n" +
                    "up 6\n" +
                    "forward 3\n" +
                    "up 2\n" +
                    "forward 9\n" +
                    "forward 2\n";

    private static final String[] INPUT_AS_LINE_ARRAY = INPUT.split("\\R");

    public static long doPuzzle1() {
        long x = 0;
        long y = 0;
        for (int step = 0; step < INPUT_AS_LINE_ARRAY.length; step++) {
            String[] commandParts = INPUT_AS_LINE_ARRAY[step].split("\\s+");
            switch (commandParts[0]) {
                case "forward":
                    x += parseLong(commandParts[1]);
                    break;

                case "down":
                    y += parseLong(commandParts[1]);
                    break;

                case "up":
                    y -= parseLong(commandParts[1]);
                    break;

                default:
                    throw new IllegalArgumentException("Input is invalid: '" + INPUT_AS_LINE_ARRAY[step] + "'.");
            }
        }
        return x * y;
    }

    public static long doPuzzle2() {
        long x = 0;
        long y = 0;
        long aim = 0;
        for (int step = 0; step < INPUT_AS_LINE_ARRAY.length; step++) {
            String[] commandParts = INPUT_AS_LINE_ARRAY[step].split("\\s+");
            switch (commandParts[0]) {
                case "forward":
                    x += parseLong(commandParts[1]);
                    y += aim * parseLong(commandParts[1]);
                    break;

                case "down":
                    aim += parseLong(commandParts[1]);
                    break;

                case "up":
                    aim -= parseLong(commandParts[1]);
                    break;

                default:
                    throw new IllegalArgumentException("Input is invalid: '" + INPUT_AS_LINE_ARRAY[step] + "'.");
            }
        }
        return x * y;
    }
}
