/* Generated By:JavaCC: Do not edit this line. CalculateConstants.java */
package com.github.rviehmann.aoc2020.Day18Part1;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalculateConstants {

    /**
     * End of File.
     */
    int EOF = 0;
    /**
     * RegularExpression Id.
     */
    int PLUS = 2;
    /**
     * RegularExpression Id.
     */
    int STAR = 3;
    /**
     * RegularExpression Id.
     */
    int OPEN_PAR = 4;
    /**
     * RegularExpression Id.
     */
    int CLOSE_PAR = 5;
    /**
     * RegularExpression Id.
     */
    int NUMBER = 6;

    /**
     * Lexical state.
     */
    int DEFAULT = 0;

    /**
     * Literal token values.
     */
    String[] tokenImage = {
            "<EOF>",
            "\" \"",
            "\"+\"",
            "\"*\"",
            "\"(\"",
            "\")\"",
            "<NUMBER>",
            };

}
