package com.github.rviehmann.aoc2020;

import java.util.HashSet;
import java.util.Set;

public class Day06 {

    // From: https://adventofcode.com/2020/day/6/input
    private static final String INPUT =
            "w\n" +
                    "s\n" +
                    "q\n" +
                    "s\n" +
                    "\n" +
                    "klfrwivqhc\n" +
                    "w\n" +
                    "wgyze\n" +
                    "anw\n" +
                    "\n" +
                    "khfraeogtbdscw\n" +
                    "rdofujgnm\n" +
                    "ydfrgo\n" +
                    "dgjoqmrf\n" +
                    "yrfdgzpon\n" +
                    "\n" +
                    "xmivszjcnqhda\n" +
                    "efwvanjd\n" +
                    "dvjuywna\n" +
                    "egjwvndkboa\n" +
                    "\n" +
                    "mraiyzpxngdl\n" +
                    "ynzdmgkxwpaiolr\n" +
                    "\n" +
                    "ur\n" +
                    "rq\n" +
                    "r\n" +
                    "\n" +
                    "xbkdvzgwuterocn\n" +
                    "zukrvtbneogdx\n" +
                    "umykaztlrodgbxwve\n" +
                    "odujhzrpsxekgbiv\n" +
                    "\n" +
                    "vhkmesczrwpj\n" +
                    "cvkmrzhsewpj\n" +
                    "\n" +
                    "rpt\n" +
                    "qwu\n" +
                    "j\n" +
                    "k\n" +
                    "p\n" +
                    "\n" +
                    "crjqtmzkba\n" +
                    "kjuhynv\n" +
                    "\n" +
                    "xjnpivhszgofwum\n" +
                    "cipqmtugyobxvwfhn\n" +
                    "\n" +
                    "qgcmjr\n" +
                    "rbmgjoq\n" +
                    "zuekypfwdng\n" +
                    "amsxg\n" +
                    "\n" +
                    "ykwj\n" +
                    "yjunwk\n" +
                    "jkwyd\n" +
                    "iwkzjy\n" +
                    "\n" +
                    "qsdczjkoixlrnyvbmgtf\n" +
                    "woickyhaguesfrnpq\n" +
                    "\n" +
                    "pma\n" +
                    "ma\n" +
                    "\n" +
                    "g\n" +
                    "n\n" +
                    "rh\n" +
                    "n\n" +
                    "\n" +
                    "tjhcxba\n" +
                    "bxthacj\n" +
                    "abhtxjc\n" +
                    "hjbaxtc\n" +
                    "jbctxha\n" +
                    "\n" +
                    "obuairedl\n" +
                    "wauixvbogejdpln\n" +
                    "ldciokbaue\n" +
                    "myblsdeuiazo\n" +
                    "tdembualfizo\n" +
                    "\n" +
                    "bpumtwsxe\n" +
                    "tsaumxw\n" +
                    "hxuftswm\n" +
                    "\n" +
                    "vqglbnuhej\n" +
                    "xbglpwzyam\n" +
                    "uelbgovc\n" +
                    "\n" +
                    "qcdwjtghispmorvlu\n" +
                    "mziopsvhdwtlgjuqrc\n" +
                    "rdlspoujmtwgihvcyq\n" +
                    "nojtaidspuhvmkblwercqg\n" +
                    "dpqohtufrcvlmjgswi\n" +
                    "\n" +
                    "jgmbovu\n" +
                    "akiuxtg\n" +
                    "\n" +
                    "rsuypgkdiofnbwt\n" +
                    "npcdvyokbirwgt\n" +
                    "mnybkgeortadpw\n" +
                    "\n" +
                    "idt\n" +
                    "idta\n" +
                    "idt\n" +
                    "idt\n" +
                    "nidtry\n" +
                    "\n" +
                    "amoxgqywpznistrlf\n" +
                    "zqfidnsbyjgaxwo\n" +
                    "nsyqijwxvohazfg\n" +
                    "sioxnqfwazgy\n" +
                    "\n" +
                    "ryhgae\n" +
                    "ahygre\n" +
                    "\n" +
                    "waopckqgeyrsuh\n" +
                    "qrkwaegysocuph\n" +
                    "csohuawqegrpky\n" +
                    "ykqahecrsoupwg\n" +
                    "\n" +
                    "eswjgdxfmkvq\n" +
                    "jmtkwbvxqfedrs\n" +
                    "\n" +
                    "eqkmozylat\n" +
                    "yjmaezkrl\n" +
                    "zbmkalye\n" +
                    "zmaekigyl\n" +
                    "ylakemzjc\n" +
                    "\n" +
                    "tqlrzgwdokxnu\n" +
                    "lkdanfmci\n" +
                    "nhmejkdflap\n" +
                    "\n" +
                    "mxviraylsouf\n" +
                    "vbspyxfaewiruqktdczl\n" +
                    "yhlravxgfisu\n" +
                    "nxyvlusafir\n" +
                    "rsvafxliyu\n" +
                    "\n" +
                    "qlrgcjdpnyzofkxmeiv\n" +
                    "kmazvnxscotrjeygdilpf\n" +
                    "zxdnogtmlqjevfkiypc\n" +
                    "pglconixjvbzkfymue\n" +
                    "\n" +
                    "zyxucs\n" +
                    "sxcy\n" +
                    "csxy\n" +
                    "xscy\n" +
                    "xscy\n" +
                    "\n" +
                    "uavrcwslpdqghmenbioxjyz\n" +
                    "kjcqgrpdnymelxuzothawvib\n" +
                    "lhbcumsfqrvzwnxjydpoagie\n" +
                    "qgozpicjumxwaybnrlvdhe\n" +
                    "\n" +
                    "vwdegcnoqafb\n" +
                    "avbwqectgnof\n" +
                    "acqefnwvgbo\n" +
                    "oeqabfwrcjlgnv\n" +
                    "ancqwovegfb\n" +
                    "\n" +
                    "qva\n" +
                    "va\n" +
                    "xba\n" +
                    "a\n" +
                    "\n" +
                    "nhxeygm\n" +
                    "oaypjdznr\n" +
                    "\n" +
                    "ngzm\n" +
                    "uhql\n" +
                    "\n" +
                    "nyujw\n" +
                    "uynw\n" +
                    "\n" +
                    "ercqboln\n" +
                    "\n" +
                    "s\n" +
                    "yh\n" +
                    "\n" +
                    "d\n" +
                    "qs\n" +
                    "n\n" +
                    "efwcn\n" +
                    "w\n" +
                    "\n" +
                    "yzowkdciuqljeg\n" +
                    "goiyjwzckludeq\n" +
                    "yuekgwjodlzicq\n" +
                    "\n" +
                    "qxkhclsg\n" +
                    "xlqckg\n" +
                    "qxkcgl\n" +
                    "\n" +
                    "nwrxtshalk\n" +
                    "fqoc\n" +
                    "ypqug\n" +
                    "pmfvzc\n" +
                    "vzigd\n" +
                    "\n" +
                    "diqentabxumf\n" +
                    "utnmieadqb\n" +
                    "udtemqinba\n" +
                    "mbqidntaeu\n" +
                    "\n" +
                    "imjpuxdlsr\n" +
                    "pmrlxsjdi\n" +
                    "xjpisrdml\n" +
                    "ialpxshdmyjr\n" +
                    "smjxzplrdi\n" +
                    "\n" +
                    "eivhrugycstznxjkawqo\n" +
                    "rhxwkizjeqayougtvncs\n" +
                    "zbsygjuwacioxpnktqvhre\n" +
                    "cyirhogexjzkwsntuavq\n" +
                    "csrovwjqxnhzayktegui\n" +
                    "\n" +
                    "h\n" +
                    "fd\n" +
                    "h\n" +
                    "\n" +
                    "uphjsebqgklcomtwify\n" +
                    "cqkltbwofhspugimeyj\n" +
                    "wvrekmaxicufgyjbhqopsltz\n" +
                    "qtobyikeschjmgflwup\n" +
                    "sceghujwtfkpblyqmio\n" +
                    "\n" +
                    "a\n" +
                    "a\n" +
                    "a\n" +
                    "a\n" +
                    "a\n" +
                    "\n" +
                    "gskndyzmophwclqv\n" +
                    "mylhsqdcnozpkgwv\n" +
                    "snyodvwplgmkzchq\n" +
                    "\n" +
                    "nyfjkgwielzq\n" +
                    "shoumqbpxg\n" +
                    "zlvkwrgaq\n" +
                    "\n" +
                    "omndevzcwyajltfksq\n" +
                    "ztfvpyjwdrlbmqoce\n" +
                    "\n" +
                    "viqrlshezknaow\n" +
                    "vheawroznstkblq\n" +
                    "hxfswlvegjnoyrkqc\n" +
                    "iblhwqneouvkrms\n" +
                    "hdpsnwqrvekol\n" +
                    "\n" +
                    "r\n" +
                    "tr\n" +
                    "srk\n" +
                    "ryz\n" +
                    "\n" +
                    "aqzkthji\n" +
                    "qkwzjta\n" +
                    "jzktqa\n" +
                    "tgzkasrojq\n" +
                    "nzikhjaqut\n" +
                    "\n" +
                    "wr\n" +
                    "wrg\n" +
                    "wr\n" +
                    "\n" +
                    "lmvpujx\n" +
                    "bczhsgfaqt\n" +
                    "\n" +
                    "fhadqpy\n" +
                    "qbk\n" +
                    "ixstvjlcrmwognuez\n" +
                    "\n" +
                    "cpuznxavj\n" +
                    "pxvuzcja\n" +
                    "cjpuzaxv\n" +
                    "upzjvaxc\n" +
                    "\n" +
                    "hftodjcxvbrisuy\n" +
                    "bhuodryvsfjxi\n" +
                    "\n" +
                    "wtdf\n" +
                    "nwuikz\n" +
                    "lxmbjawysh\n" +
                    "kdrtw\n" +
                    "qfkw\n" +
                    "\n" +
                    "ymxzrfh\n" +
                    "zrwjdhf\n" +
                    "\n" +
                    "lniw\n" +
                    "wnli\n" +
                    "wnzrli\n" +
                    "\n" +
                    "ubwjo\n" +
                    "sjzo\n" +
                    "rjo\n" +
                    "\n" +
                    "zikumqlvjobw\n" +
                    "ktoaufevgrb\n" +
                    "rnkbtovduh\n" +
                    "\n" +
                    "jmvbntqilzhrgp\n" +
                    "qhgzvkmtripw\n" +
                    "psrqwgihzvtm\n" +
                    "vmgqrtpihzd\n" +
                    "vqrwipgmthsz\n" +
                    "\n" +
                    "hnyzvkwgeo\n" +
                    "ezhvoynk\n" +
                    "evnhkoqwzy\n" +
                    "hvznelgkoy\n" +
                    "oyekhaxviznu\n" +
                    "\n" +
                    "pwqivtzgebnolk\n" +
                    "inqwtvgzopb\n" +
                    "qwinobvgzpt\n" +
                    "vbiowqtpnzg\n" +
                    "\n" +
                    "ulsvitcxngwzhryaebkfp\n" +
                    "sxypjlzgoihkrnubva\n" +
                    "\n" +
                    "bzgt\n" +
                    "gotxzb\n" +
                    "ztgb\n" +
                    "tbglz\n" +
                    "\n" +
                    "lsrqikouybjdvawz\n" +
                    "qnchepfoi\n" +
                    "\n" +
                    "ufwavmp\n" +
                    "vfpamwu\n" +
                    "wfvmpau\n" +
                    "vwumfpa\n" +
                    "pmtfuawv\n" +
                    "\n" +
                    "g\n" +
                    "gh\n" +
                    "e\n" +
                    "n\n" +
                    "\n" +
                    "swfjhadxgnuzrybokl\n" +
                    "sleobifpuqhkzc\n" +
                    "\n" +
                    "pcwfrnhsvdgejimlzoaubk\n" +
                    "vducpzwnsjmhoilgkbaerf\n" +
                    "rpbjnwvguahecofmkisdzl\n" +
                    "ufbxshgloznvrwipjcqeadmk\n" +
                    "hnmscakpleigdfjozvburw\n" +
                    "\n" +
                    "ouraitbgl\n" +
                    "trdmgi\n" +
                    "fcxpstnyjg\n" +
                    "gouat\n" +
                    "\n" +
                    "nmrvxhdc\n" +
                    "chnrmvxd\n" +
                    "xvrhcnmd\n" +
                    "mrcdvxhn\n" +
                    "mxvndhcr\n" +
                    "\n" +
                    "cufsjilngrbydkhqex\n" +
                    "kljdhfaxyguqisbrw\n" +
                    "dkgubshipmxrlqftoyj\n" +
                    "\n" +
                    "jsi\n" +
                    "sij\n" +
                    "sji\n" +
                    "isj\n" +
                    "jis\n" +
                    "\n" +
                    "prnxkmutl\n" +
                    "pdvuaeyxochzltnkmr\n" +
                    "gmxlutkpnrb\n" +
                    "lxpmkrtnu\n" +
                    "\n" +
                    "amcxhzlrpg\n" +
                    "kpmowcr\n" +
                    "\n" +
                    "n\n" +
                    "ryn\n" +
                    "an\n" +
                    "n\n" +
                    "\n" +
                    "qfgeuyn\n" +
                    "unqcfe\n" +
                    "\n" +
                    "haj\n" +
                    "ocja\n" +
                    "\n" +
                    "tbfmzce\n" +
                    "tfmzbe\n" +
                    "smzefbt\n" +
                    "mbztfe\n" +
                    "mfztbe\n" +
                    "\n" +
                    "cgrtbynxejvqmhalf\n" +
                    "hyafxecjqvrnmbltg\n" +
                    "qtghbfrmcxaevjlny\n" +
                    "fyqjgcemhlabnrtxv\n" +
                    "\n" +
                    "h\n" +
                    "h\n" +
                    "h\n" +
                    "wh\n" +
                    "hg\n" +
                    "\n" +
                    "mpidnesyhcowqtgulfk\n" +
                    "oehmlsxqundfgbkytwa\n" +
                    "\n" +
                    "hsqywtmpgazudj\n" +
                    "tpuewnhoagzsydjlm\n" +
                    "gdupwstzjahym\n" +
                    "qwrpgikdyuatzhjms\n" +
                    "mtaduhswzjpgy\n" +
                    "\n" +
                    "yfcirgulotspbxehdzmwnkqv\n" +
                    "aqvgyhtrniemlxpbcudwsf\n" +
                    "\n" +
                    "bguysvaqwcmdjk\n" +
                    "xmgfuybtkprqacd\n" +
                    "\n" +
                    "rjmoslapxkvuht\n" +
                    "uavxpsflhjoktr\n" +
                    "hpcjtarlsqwkoxuv\n" +
                    "jvakpxloushtr\n" +
                    "\n" +
                    "iwcnso\n" +
                    "bgwc\n" +
                    "gpwcu\n" +
                    "\n" +
                    "jwdiuyabzklmqsxv\n" +
                    "uxyjkvqwdszflabmi\n" +
                    "aiqwuszlxbkjydvm\n" +
                    "vysjdmqlzwxaibku\n" +
                    "mksabwzxqivujdly\n" +
                    "\n" +
                    "a\n" +
                    "alo\n" +
                    "a\n" +
                    "a\n" +
                    "a\n" +
                    "\n" +
                    "dzushfvegcopkbw\n" +
                    "oueshcbkvdpwg\n" +
                    "esbcowkgvpduh\n" +
                    "pghduksijcevywobl\n" +
                    "puezsvdohbwckg\n" +
                    "\n" +
                    "ymow\n" +
                    "moy\n" +
                    "ohmyle\n" +
                    "ymo\n" +
                    "moy\n" +
                    "\n" +
                    "mzctqbypdkrialjgoxsf\n" +
                    "kqpoyabcigszdrtmfljx\n" +
                    "xkfgltdipzjqysacmbro\n" +
                    "lirmkbxsafcgdozytjpq\n" +
                    "\n" +
                    "yhtvcsfaigk\n" +
                    "wrevhoqdm\n" +
                    "zphujdrlnv\n" +
                    "\n" +
                    "zyahfewvcs\n" +
                    "sfzcweayh\n" +
                    "woeshuacyf\n" +
                    "\n" +
                    "p\n" +
                    "ljbr\n" +
                    "wxp\n" +
                    "\n" +
                    "cfdltixjupqon\n" +
                    "nmuptcqodlfij\n" +
                    "rpltfunoqjicd\n" +
                    "nlqctporjifud\n" +
                    "ufipcdtlnojq\n" +
                    "\n" +
                    "xu\n" +
                    "uowa\n" +
                    "ux\n" +
                    "\n" +
                    "ycloxsvrwajqbzfkhpgmun\n" +
                    "wjlrmuoaxvkqfbpzsyhcng\n" +
                    "aqrcybjgonhkpuvmzlfxsw\n" +
                    "warfnczvokmyjgsqxhblpu\n" +
                    "tvzngwyqbfulxcphoskjrma\n" +
                    "\n" +
                    "yfhzaw\n" +
                    "hmuazqwbj\n" +
                    "ayhzwi\n" +
                    "awxetzh\n" +
                    "gawzih\n" +
                    "\n" +
                    "gsbqoynfmevkcadjzu\n" +
                    "dmyofukqezgasctvn\n" +
                    "zqkmoadfnubsiveygc\n" +
                    "gezqymskdfnouvaci\n" +
                    "kzgncourmyfqeavsd\n" +
                    "\n" +
                    "pzkyu\n" +
                    "pyedw\n" +
                    "ypr\n" +
                    "tyifxjnsp\n" +
                    "rbkqywup\n" +
                    "\n" +
                    "mlwtuqxsog\n" +
                    "xzmusgwtlq\n" +
                    "qmitxvulsgwcak\n" +
                    "uxwgjmrtslq\n" +
                    "\n" +
                    "bcnkpwtmqgorsfxy\n" +
                    "hmogknxfpqwsctbr\n" +
                    "gqsracvfiobzkxnpmw\n" +
                    "\n" +
                    "kpxv\n" +
                    "pfkzxv\n" +
                    "xpk\n" +
                    "pkx\n" +
                    "xubokps\n" +
                    "\n" +
                    "bwlytxgviueczfqakrpsmhojd\n" +
                    "fowlhcmvasbqdgptjikyxruze\n" +
                    "\n" +
                    "nowi\n" +
                    "ivonqx\n" +
                    "if\n" +
                    "lysuabtiprdkzh\n" +
                    "\n" +
                    "u\n" +
                    "u\n" +
                    "u\n" +
                    "\n" +
                    "dkrhoamveqlgcjwfsz\n" +
                    "dgokizyvfjhaqwcme\n" +
                    "thwguqxoadznekvcjpmbf\n" +
                    "\n" +
                    "hyrsn\n" +
                    "rhdyjsf\n" +
                    "ycbzrs\n" +
                    "smrykotpu\n" +
                    "\n" +
                    "tsnfogyic\n" +
                    "ingctoysf\n" +
                    "\n" +
                    "cvnoazqpkthxwj\n" +
                    "qhsmjdlznvkwfbt\n" +
                    "qnvkhjwlstz\n" +
                    "ltjzkugbqhwvnis\n" +
                    "\n" +
                    "q\n" +
                    "ytx\n" +
                    "\n" +
                    "vxjyeorpcgbsta\n" +
                    "oajbxtysv\n" +
                    "tymsxjoabv\n" +
                    "\n" +
                    "jwko\n" +
                    "wojk\n" +
                    "wjko\n" +
                    "\n" +
                    "nfjvu\n" +
                    "nfkv\n" +
                    "dvnfse\n" +
                    "\n" +
                    "toe\n" +
                    "toe\n" +
                    "ote\n" +
                    "\n" +
                    "zqrmchysuf\n" +
                    "oyzufmqslke\n" +
                    "\n" +
                    "sgbwp\n" +
                    "pgwbs\n" +
                    "\n" +
                    "bl\n" +
                    "klp\n" +
                    "led\n" +
                    "l\n" +
                    "lq\n" +
                    "\n" +
                    "ea\n" +
                    "ea\n" +
                    "rfeah\n" +
                    "ae\n" +
                    "aex\n" +
                    "\n" +
                    "kbpnxtliue\n" +
                    "kxbtieunp\n" +
                    "exbtipuknr\n" +
                    "nburkipxtel\n" +
                    "igtpwhnejqbuckx\n" +
                    "\n" +
                    "hfarpblqs\n" +
                    "baophlqrexfsd\n" +
                    "hbqfsnlpar\n" +
                    "\n" +
                    "fspkvb\n" +
                    "hfpkvsb\n" +
                    "vpsfkb\n" +
                    "\n" +
                    "fbnx\n" +
                    "fknl\n" +
                    "nftl\n" +
                    "cuzownfq\n" +
                    "fyn\n" +
                    "\n" +
                    "qd\n" +
                    "qfdzy\n" +
                    "dq\n" +
                    "\n" +
                    "jhwgyisz\n" +
                    "vfkcdjqhme\n" +
                    "hxwjo\n" +
                    "jyhbr\n" +
                    "hsuj\n" +
                    "\n" +
                    "bip\n" +
                    "jolwnbcgp\n" +
                    "reptb\n" +
                    "pbz\n" +
                    "bpe\n" +
                    "\n" +
                    "hrdiepna\n" +
                    "vitecpzyndar\n" +
                    "esbkaudrijpnlog\n" +
                    "pxivdaenrh\n" +
                    "\n" +
                    "hpfwjy\n" +
                    "fjya\n" +
                    "ajyf\n" +
                    "yfj\n" +
                    "\n" +
                    "r\n" +
                    "rz\n" +
                    "r\n" +
                    "r\n" +
                    "r\n" +
                    "\n" +
                    "r\n" +
                    "r\n" +
                    "r\n" +
                    "\n" +
                    "sqlcpxhtouyzwv\n" +
                    "tyxhrsbuczklidogvq\n" +
                    "\n" +
                    "aisdgc\n" +
                    "mcdsiga\n" +
                    "asigdc\n" +
                    "dcisag\n" +
                    "\n" +
                    "iswu\n" +
                    "siw\n" +
                    "sqwi\n" +
                    "\n" +
                    "aixlbtqznjcgshu\n" +
                    "oayljitqguzbchxns\n" +
                    "suxgbcntaliqjzh\n" +
                    "\n" +
                    "fubhpe\n" +
                    "ufibkay\n" +
                    "\n" +
                    "lena\n" +
                    "izaj\n" +
                    "axbvk\n" +
                    "chav\n" +
                    "\n" +
                    "fkoshgqju\n" +
                    "jiq\n" +
                    "qjwbi\n" +
                    "jiq\n" +
                    "jyqbi\n" +
                    "\n" +
                    "ebaqscfvhgtuoirnjwxlzykp\n" +
                    "hfjxqtuvrwgeknboipazyscl\n" +
                    "\n" +
                    "qrdo\n" +
                    "qlfejdru\n" +
                    "pqxyra\n" +
                    "\n" +
                    "gmnafo\n" +
                    "fsgmepna\n" +
                    "mfonag\n" +
                    "\n" +
                    "pnxtgjqsbizkyc\n" +
                    "ithkycsjbpzxru\n" +
                    "\n" +
                    "snfwtloepqdrkiy\n" +
                    "qkobliwsdnh\n" +
                    "wsxjqnihzkodl\n" +
                    "ahdwsilnkqbo\n" +
                    "duowiqcmksnl\n" +
                    "\n" +
                    "cjft\n" +
                    "haorelpitd\n" +
                    "gbxhedt\n" +
                    "knzthvyaqu\n" +
                    "\n" +
                    "vgyoklbrhedtwcjxans\n" +
                    "eaxgovbrudfnhzktjsyclw\n" +
                    "ytcgjxvodwhaenlsbrk\n" +
                    "\n" +
                    "fnmhxj\n" +
                    "lfnxr\n" +
                    "xmnefc\n" +
                    "wduktfvqgn\n" +
                    "\n" +
                    "omf\n" +
                    "jwfou\n" +
                    "cpdgxqevabkrzny\n" +
                    "lwhts\n" +
                    "\n" +
                    "vhn\n" +
                    "hirkuj\n" +
                    "hzngm\n" +
                    "\n" +
                    "minhkslfp\n" +
                    "rfahobpksn\n" +
                    "plfknsch\n" +
                    "psifmcnhk\n" +
                    "\n" +
                    "xkoiztsqvpceywhfbndu\n" +
                    "ebkpvsunzcxhmofdiqyt\n" +
                    "\n" +
                    "nfp\n" +
                    "fne\n" +
                    "fn\n" +
                    "\n" +
                    "hinmuatrvygoqxfsjc\n" +
                    "vrfxtuagojyiqnhscm\n" +
                    "tifguysjoxrnqmadhcv\n" +
                    "\n" +
                    "yetihjzfkndum\n" +
                    "nejhiatzumkyd\n" +
                    "zitvhkdenmjyu\n" +
                    "hinjeumtzykd\n" +
                    "ekztmhndjiuy\n" +
                    "\n" +
                    "glbtefawdsycomj\n" +
                    "djbsgnalyokcwmte\n" +
                    "mojdwysnategclb\n" +
                    "bvgcjosaytwldemp\n" +
                    "\n" +
                    "evwuatlypjixqzrsmhc\n" +
                    "erwiucsaxmtvhyjzl\n" +
                    "lhcxeavjmyzurtsonwip\n" +
                    "mxveyutrhslgbaczdjifw\n" +
                    "snmyhxctuazerkwlvji\n" +
                    "\n" +
                    "rvpwjbh\n" +
                    "yfecq\n" +
                    "\n" +
                    "vxbchwiygoe\n" +
                    "gwivcydbxeho\n" +
                    "ylogwcevibhtxa\n" +
                    "bgwphicvexyo\n" +
                    "emivwogychrbx\n" +
                    "\n" +
                    "pwghmnxtfzbyl\n" +
                    "vqsakujrdo\n" +
                    "\n" +
                    "areduqjvczsm\n" +
                    "jadhzebrcum\n" +
                    "dcrumqayjzei\n" +
                    "rczsujymdea\n" +
                    "\n" +
                    "omtyndvrha\n" +
                    "vwdhaort\n" +
                    "\n" +
                    "crb\n" +
                    "r\n" +
                    "\n" +
                    "uirepncmbyhzkaofwxvd\n" +
                    "recwkxyhfnbmzaduovs\n" +
                    "kwceyznjbfoidhamrxvu\n" +
                    "\n" +
                    "lejmaipctkvuwgzqfsnor\n" +
                    "okmuaizfsrtnwlevjcgqp\n" +
                    "lqkwnraeuovstmizpjcgf\n" +
                    "atsunvqljzepckrmogwif\n" +
                    "\n" +
                    "rjobteshildmxacpz\n" +
                    "lrpdbajtmhcsoexiz\n" +
                    "\n" +
                    "l\n" +
                    "pvnsiom\n" +
                    "khgx\n" +
                    "f\n" +
                    "f\n" +
                    "\n" +
                    "khjgfwy\n" +
                    "fpgykjw\n" +
                    "\n" +
                    "wajntv\n" +
                    "wdzuvtj\n" +
                    "iowjvtke\n" +
                    "\n" +
                    "fwvopmi\n" +
                    "singjtf\n" +
                    "\n" +
                    "nocq\n" +
                    "nugbvmqeo\n" +
                    "qaoscn\n" +
                    "\n" +
                    "rlkzoi\n" +
                    "opfsta\n" +
                    "qvuo\n" +
                    "soxp\n" +
                    "xhmoj\n" +
                    "\n" +
                    "guvqownkfrilte\n" +
                    "aegnhfyxcszqbwvl\n" +
                    "\n" +
                    "qzo\n" +
                    "qlr\n" +
                    "vquo\n" +
                    "fgq\n" +
                    "nkwhbdactmxijq\n" +
                    "\n" +
                    "ijqgmnkeoxwuvbta\n" +
                    "tiubnkgwamoqvj\n" +
                    "ajdkuqtimbpvonhgw\n" +
                    "mjgnyqitvwraobuk\n" +
                    "\n" +
                    "s\n" +
                    "g\n" +
                    "g\n" +
                    "g\n" +
                    "\n" +
                    "vspbciqmaj\n" +
                    "pijumqscva\n" +
                    "\n" +
                    "evpqzoxgtmbns\n" +
                    "tevgqbpfsnxl\n" +
                    "epnbtgsxvq\n" +
                    "qxpsnetgmvb\n" +
                    "depavkqngtrbjxs\n" +
                    "\n" +
                    "aplrhkuiyf\n" +
                    "mxhpvwfzolsn\n" +
                    "\n" +
                    "fxtbhediuslacmy\n" +
                    "hbkufmistx\n" +
                    "ihupfsmtbxz\n" +
                    "mfhipusxtb\n" +
                    "xihmtjbsuf\n" +
                    "\n" +
                    "muzqcfp\n" +
                    "mcpfzu\n" +
                    "mrzfpucw\n" +
                    "zfcvmup\n" +
                    "pzcufm\n" +
                    "\n" +
                    "q\n" +
                    "q\n" +
                    "q\n" +
                    "q\n" +
                    "\n" +
                    "jbk\n" +
                    "peiw\n" +
                    "\n" +
                    "vuejaotbcp\n" +
                    "ulbakiotxdcry\n" +
                    "cobunat\n" +
                    "bmcfvhauto\n" +
                    "\n" +
                    "qpo\n" +
                    "qopw\n" +
                    "pqo\n" +
                    "\n" +
                    "ckpequzlfdtrb\n" +
                    "yphsdgwbzn\n" +
                    "bgmpzd\n" +
                    "\n" +
                    "nbuqtywiloaesz\n" +
                    "rkghxdvf\n" +
                    "\n" +
                    "owetrs\n" +
                    "etbwciulf\n" +
                    "\n" +
                    "heaudnstmjwrpg\n" +
                    "pxkyniszuebmolhfjdgr\n" +
                    "jenrsqcupdwhmg\n" +
                    "pujhrdmcengs\n" +
                    "\n" +
                    "cutnl\n" +
                    "ltunc\n" +
                    "cntlu\n" +
                    "\n" +
                    "hd\n" +
                    "bih\n" +
                    "\n" +
                    "rdf\n" +
                    "drf\n" +
                    "\n" +
                    "kftwxpoqmgbuil\n" +
                    "wfstpikuhqbcmxog\n" +
                    "zktqfjpxayobvumin\n" +
                    "qgtfbopkruidmx\n" +
                    "\n" +
                    "sovyuxi\n" +
                    "vux\n" +
                    "uvqx\n" +
                    "\n" +
                    "j\n" +
                    "j\n" +
                    "j\n" +
                    "j\n" +
                    "mav\n" +
                    "\n" +
                    "qark\n" +
                    "tdeaquk\n" +
                    "zaxnwcpylkgvoqmhi\n" +
                    "kaq\n" +
                    "\n" +
                    "rfysxdtumlwavingkhqo\n" +
                    "gbudftnxypmzrlevakjoq\n" +
                    "\n" +
                    "qafyltcembujhd\n" +
                    "jmaqtdublyfche\n" +
                    "dmhbqljfeaytuc\n" +
                    "emdtqyjahucbfl\n" +
                    "tcbfjlyemaqudh\n" +
                    "\n" +
                    "cpxhbjlqwarm\n" +
                    "bhlzcawpjmqyg\n" +
                    "cjlwbamhqpe\n" +
                    "fhlbjcmpqawv\n" +
                    "jalmbqiphwc\n" +
                    "\n" +
                    "zoyw\n" +
                    "yzo\n" +
                    "\n" +
                    "qvudhfxtjesibgwynaorl\n" +
                    "nuctmlvpkgoefqsihbrwyzxa\n" +
                    "\n" +
                    "mgkqthideusny\n" +
                    "ohtgleqksudiynm\n" +
                    "nhgikyustdqme\n" +
                    "puqgrdyntmhkise\n" +
                    "\n" +
                    "hlmfcir\n" +
                    "lcmfrih\n" +
                    "rlkcyfmhin\n" +
                    "imhcrlf\n" +
                    "\n" +
                    "ifqds\n" +
                    "spodiqf\n" +
                    "ifdsq\n" +
                    "\n" +
                    "ajp\n" +
                    "apj\n" +
                    "\n" +
                    "dramqyjeiskugn\n" +
                    "qidmekaysrgpjfun\n" +
                    "egysqnkrijluadm\n" +
                    "ngdirjyksameqlu\n" +
                    "\n" +
                    "tmpogzdsxrye\n" +
                    "sryedpmqxzg\n" +
                    "zcxpmlsukydreg\n" +
                    "dpeolsyxkwgtzijrm\n" +
                    "mefyrxdpbsvghz\n" +
                    "\n" +
                    "qafgj\n" +
                    "agfjd\n" +
                    "\n" +
                    "hrczjfebg\n" +
                    "fjergzc\n" +
                    "cfmrztsygvl\n" +
                    "\n" +
                    "istujvdk\n" +
                    "keyoahi\n" +
                    "\n" +
                    "ktwuhfqas\n" +
                    "qksmthdwaru\n" +
                    "ajkthusqpw\n" +
                    "\n" +
                    "eprjtfahignbcklvuqwyx\n" +
                    "apxqrceguwtjnkbhyfilv\n" +
                    "\n" +
                    "drosxgbv\n" +
                    "orvbgx\n" +
                    "xgrobv\n" +
                    "\n" +
                    "ylmpr\n" +
                    "yrmlp\n" +
                    "\n" +
                    "auwizmytjcsdbnvo\n" +
                    "ywsmkoatibzndcju\n" +
                    "nytqecdbxhlzmiwuoarsgj\n" +
                    "vtdowcfjymsauknbiz\n" +
                    "\n" +
                    "z\n" +
                    "z\n" +
                    "z\n" +
                    "z\n" +
                    "\n" +
                    "hxjiqdaveoku\n" +
                    "jxqkdvheioau\n" +
                    "hxoqdueajvki\n" +
                    "\n" +
                    "tuxfs\n" +
                    "usxtf\n" +
                    "uxtfs\n" +
                    "\n" +
                    "dnaiovgxlryzhqwepbmuj\n" +
                    "zbgxvpaudnmwrqohejyil\n" +
                    "\n" +
                    "qaybxdnelzokvjhmwrgusiftp\n" +
                    "pyoukjfretqzsdxmhwvna\n" +
                    "szwcvfkohpuyeqntrdamxj\n" +
                    "jzkrfqvyptahxsmnowdue\n" +
                    "yepoudnfxzkwjmqvtrsha\n" +
                    "\n" +
                    "pd\n" +
                    "e\n" +
                    "m\n" +
                    "lq\n" +
                    "\n" +
                    "xcyvzopaubf\n" +
                    "zhuyovbpcx\n" +
                    "bcxuyvgzhop\n" +
                    "dyczxoubvpmsw\n" +
                    "zovykxucpb\n" +
                    "\n" +
                    "w\n" +
                    "w\n" +
                    "w\n" +
                    "h\n" +
                    "\n" +
                    "aohk\n" +
                    "kao\n" +
                    "vkyhoa\n" +
                    "oqvak\n" +
                    "akjow\n" +
                    "\n" +
                    "r\n" +
                    "r\n" +
                    "g\n" +
                    "r\n" +
                    "\n" +
                    "clnhiwztgq\n" +
                    "ydfxzrcvjg\n" +
                    "\n" +
                    "otmchepjl\n" +
                    "gkvunyfwlm\n" +
                    "\n" +
                    "ruzxit\n" +
                    "ixtzdr\n" +
                    "xrzit\n" +
                    "xqzitckr\n" +
                    "trizux\n" +
                    "\n" +
                    "grufeslzwvxqndhimakcyjp\n" +
                    "soaxtzmwgjdlnkpcqevrfuiy\n" +
                    "bdaxjepnmzkruslyvqifwcg\n" +
                    "qjiysmvhxfurkaegzdwlpcn\n" +
                    "\n" +
                    "cerjstxhanlzkqgodfuy\n" +
                    "crjsonqyuvdaelhftxzgk\n" +
                    "rksaucfxdgmoqnhytejzl\n" +
                    "gsnuojthickrealfzdyqx\n" +
                    "\n" +
                    "wmstjfqhvaplord\n" +
                    "fgnejqhkouizpvt\n" +
                    "\n" +
                    "ojzucmk\n" +
                    "upvmaozj\n" +
                    "uhimrxjoqgzbw\n" +
                    "utzjoemk\n" +
                    "vztojmeu\n" +
                    "\n" +
                    "elqmorhugsxypbtza\n" +
                    "ogtlyehzpfaqxurbms\n" +
                    "eqbgrxhauymptlzso\n" +
                    "\n" +
                    "xldewg\n" +
                    "lgdxznew\n" +
                    "zexwgld\n" +
                    "ldwxge\n" +
                    "bghlxviwed\n" +
                    "\n" +
                    "pgqovbkfxciz\n" +
                    "fqobpzxkct\n" +
                    "czqfxpbko\n" +
                    "\n" +
                    "h\n" +
                    "h\n" +
                    "w\n" +
                    "h\n" +
                    "h\n" +
                    "\n" +
                    "gw\n" +
                    "wg\n" +
                    "wg\n" +
                    "gw\n" +
                    "gew\n" +
                    "\n" +
                    "byvadoriwmkhfqtcznglusxpje\n" +
                    "xmwvnjpglyeocqhfarusbkzdti\n" +
                    "zlrgmsbhinxvqueojtfawdcpky\n" +
                    "pwghxcjybruidskelqmvaonftz\n" +
                    "\n" +
                    "zwqlxogbvtuafeh\n" +
                    "xrhaelugfwkoztb\n" +
                    "zytuelfhoawxgb\n" +
                    "deglztxbouawhf\n" +
                    "xuageoztfhlbw\n" +
                    "\n" +
                    "rqydeszwhu\n" +
                    "uwzydhqcers\n" +
                    "yqsdhruewz\n" +
                    "reyhqdzsuwn\n" +
                    "\n" +
                    "bomazjw\n" +
                    "wzabmjno\n" +
                    "jamzowb\n" +
                    "ojawbzm\n" +
                    "wbhzfamjo\n" +
                    "\n" +
                    "pxzofjkney\n" +
                    "aedkui\n" +
                    "\n" +
                    "iezhxcldqrasu\n" +
                    "givchplftdorun\n" +
                    "\n" +
                    "xy\n" +
                    "gydxv\n" +
                    "\n" +
                    "igduyfakwjeot\n" +
                    "utewfoajykid\n" +
                    "\n" +
                    "cvudfonrqshzbgyemtkxlap\n" +
                    "fxlapvmdcqzybugnhrketso\n" +
                    "fkbersnvythqodmuaglzxpc\n" +
                    "luqerdogftkmxnyzvsbahcp\n" +
                    "fsolzkxvdtughqmabcyrpne\n" +
                    "\n" +
                    "zwayveu\n" +
                    "dvpwyiztgae\n" +
                    "yzeuawv\n" +
                    "evarwyz\n" +
                    "\n" +
                    "tpkeivrucdhsawmn\n" +
                    "imspcednuvw\n" +
                    "epmnvlicsdwu\n" +
                    "icmupenvdws\n" +
                    "fmswudvpeionc\n" +
                    "\n" +
                    "nbekcurq\n" +
                    "rnckqbeu\n" +
                    "qrlkcnbuv\n" +
                    "buerqkcn\n" +
                    "\n" +
                    "jylehvp\n" +
                    "ejvlyph\n" +
                    "ypjvhegl\n" +
                    "ehpylvj\n" +
                    "hlvyjfep\n" +
                    "\n" +
                    "cnwjxzisphtdgveqky\n" +
                    "njqvwdyhitocxzkpesg\n" +
                    "teywxgihcsvdkjpzqn\n" +
                    "hdiqyntzgxwejpsvkc\n" +
                    "\n" +
                    "a\n" +
                    "a\n" +
                    "ma\n" +
                    "\n" +
                    "cd\n" +
                    "cj\n" +
                    "\n" +
                    "nzekclihqfyrovdwgtusm\n" +
                    "eosqnkxdpcuftzhwjmrily\n" +
                    "ynimldrewskufczohqt\n" +
                    "foreinluhctqkyszmdw\n" +
                    "\n" +
                    "gxwfcasjqbnoyrv\n" +
                    "cnqjyfvwgas\n" +
                    "vfqangjcwuys\n" +
                    "\n" +
                    "en\n" +
                    "jn\n" +
                    "n\n" +
                    "gnzdf\n" +
                    "\n" +
                    "knarqm\n" +
                    "lknhmars\n" +
                    "\n" +
                    "wpenjuhd\n" +
                    "krucdjzb\n" +
                    "nutjhd\n" +
                    "\n" +
                    "xiejmt\n" +
                    "cijktnpxme\n" +
                    "pmixcj\n" +
                    "xoijm\n" +
                    "bzjqrmighx\n" +
                    "\n" +
                    "ftucvebloxijamnzwy\n" +
                    "vqxtyiucdlnfbzaj\n" +
                    "cntxajbfslviukzy\n" +
                    "cbtxlzjfsudvinay\n" +
                    "dvftjyizuxnbacl\n" +
                    "\n" +
                    "ty\n" +
                    "ry\n" +
                    "y\n" +
                    "\n" +
                    "kanrgxtibzsjydf\n" +
                    "pscfavzqyb\n" +
                    "blasyzfcvum\n" +
                    "wfhzasbey\n" +
                    "ampozwyfbuqs\n" +
                    "\n" +
                    "ihmpuwjfvygbnze\n" +
                    "vzgcwefnihymxpubs\n" +
                    "hvmbuwznygpife\n" +
                    "vzdiknatrgmhyebwfoulp\n" +
                    "\n" +
                    "hretmjgxwcidl\n" +
                    "hjkiedvmcglx\n" +
                    "jdmilhxewgc\n" +
                    "clhgbjndxie\n" +
                    "\n" +
                    "gnabr\n" +
                    "rnbga\n" +
                    "bywnuar\n" +
                    "\n" +
                    "lhd\n" +
                    "d\n" +
                    "mqdbo\n" +
                    "ahd\n" +
                    "d\n" +
                    "\n" +
                    "kisuyql\n" +
                    "qsymkglu\n" +
                    "skvuiyplq\n" +
                    "\n" +
                    "xhyabuesjpd\n" +
                    "lxagr\n" +
                    "xzlaqt\n" +
                    "\n" +
                    "kepiznwbyas\n" +
                    "gyfirmnbodztsv\n" +
                    "\n" +
                    "b\n" +
                    "b\n" +
                    "b\n" +
                    "b\n" +
                    "\n" +
                    "zskcmdxeaogqbu\n" +
                    "zmbscodakqupxge\n" +
                    "\n" +
                    "e\n" +
                    "j\n" +
                    "b\n" +
                    "q\n" +
                    "\n" +
                    "blvwcsymj\n" +
                    "vwjsymbcl\n" +
                    "wbmlcyjsv\n" +
                    "mwjvcybsl\n" +
                    "symvcblwj\n" +
                    "\n" +
                    "yivbad\n" +
                    "dayibv\n" +
                    "bviayd\n" +
                    "idvyba\n" +
                    "ivadby\n" +
                    "\n" +
                    "atzulnbxedjgq\n" +
                    "egbvijuzyxtqadl\n" +
                    "ladebjzrtgu\n" +
                    "blzdjetaug\n" +
                    "ehpzmcdgtuasbkolj\n" +
                    "\n" +
                    "vejskrgaqnbltxiy\n" +
                    "bviglyatsrno\n" +
                    "iwcbrlysgvntad\n" +
                    "gsliobcrynavtp\n" +
                    "\n" +
                    "ybowxj\n" +
                    "sufavcpghd\n" +
                    "\n" +
                    "fjcikx\n" +
                    "cjxki\n" +
                    "cjxmik\n" +
                    "xjkic\n" +
                    "cjxki\n" +
                    "\n" +
                    "o\n" +
                    "tz\n" +
                    "p\n" +
                    "o\n" +
                    "p\n" +
                    "\n" +
                    "f\n" +
                    "h\n" +
                    "f\n" +
                    "f\n" +
                    "f\n" +
                    "\n" +
                    "n\n" +
                    "n\n" +
                    "din\n" +
                    "\n" +
                    "udlnyspztvcf\n" +
                    "uzpdhtcayv\n" +
                    "ydhzcvutp\n" +
                    "\n" +
                    "teylnzmf\n" +
                    "lntmefzy\n" +
                    "lnztyemf\n" +
                    "\n" +
                    "ugwcfqzrpsdxhnyv\n" +
                    "ldfosniyuwxhcvbg\n" +
                    "lxvdumygwfsnch\n" +
                    "vcowxgynhusfd\n" +
                    "\n" +
                    "qwxuykodtpehbzmgsrc\n" +
                    "nyxqougapktdbh\n" +
                    "ykdpbxtfquohg\n" +
                    "tubxpdygoqhk\n" +
                    "\n" +
                    "zgyomlb\n" +
                    "moglkbzy\n" +
                    "yogbclmz\n" +
                    "\n" +
                    "qrejtivfwzubyknaplhmgcodxs\n" +
                    "witcplundkhaqxeryvbzsgfojm\n" +
                    "\n" +
                    "fvoindcxqhzabketlug\n" +
                    "xgdqizetlhvkubaofcn\n" +
                    "xciztehdlufnkvboagq\n" +
                    "\n" +
                    "hbolxizvkmctw\n" +
                    "udoarnhsjwk\n" +
                    "owdrhsk\n" +
                    "ghfwkyoea\n" +
                    "\n" +
                    "cfzkvieqtoagsln\n" +
                    "egtolisqrcf\n" +
                    "stlqcifgoe\n" +
                    "\n" +
                    "erjlptikwqoczdgubanxvf\n" +
                    "evaqfnxljitbkdwucozrpg\n" +
                    "\n" +
                    "ojqbicpwexfglrvyastzk\n" +
                    "pzvisdhlortfqjxkwgacyeb\n" +
                    "\n" +
                    "xiezsdhj\n" +
                    "hwvgtplfs\n" +
                    "hioskr\n" +
                    "\n" +
                    "atyqbkzlw\n" +
                    "bzakwqylt\n" +
                    "ovwpzaybqktjl\n" +
                    "ylakwtbqz\n" +
                    "\n" +
                    "flxozwatvkcmibjn\n" +
                    "wcxhokusjzvmbtn\n" +
                    "\n" +
                    "jm\n" +
                    "n\n" +
                    "\n" +
                    "vmtwznjklocridexufapb\n" +
                    "nztijrefwxuvkmacdplb\n" +
                    "wjtipvfzenlmcrxuadbk\n" +
                    "vpyefticjsxrzdauwnkbml\n" +
                    "\n" +
                    "sjryquvzi\n" +
                    "qvzsiuryj\n" +
                    "vyjruqsiz\n" +
                    "quykrjszvi\n" +
                    "\n" +
                    "iqgpeslwatumyvxrkndhcjb\n" +
                    "gcdqpktlmuzwjrvbsinha\n" +
                    "usbcltqjmvpagndkrwhi\n" +
                    "hkatgblrqpidnwjumvsc\n" +
                    "\n" +
                    "ijrwnhlfsaxuy\n" +
                    "cyzdt\n" +
                    "cyvpm\n" +
                    "qpkybtoe\n" +
                    "\n" +
                    "agtpnyvweqrmohfil\n" +
                    "lmtwhfgyzneaipq\n" +
                    "yianftmwsgqlpeh\n" +
                    "ezfsihltawgpnbmqy\n" +
                    "\n" +
                    "fvdj\n" +
                    "djv\n" +
                    "\n" +
                    "jybuhgeapvnk\n" +
                    "qdmscixzlto\n" +
                    "wpvgfar\n" +
                    "\n" +
                    "dtlbwgjyxphmqus\n" +
                    "hkjxdtvqngyzar\n" +
                    "\n" +
                    "i\n" +
                    "i\n" +
                    "v\n" +
                    "\n" +
                    "jpbamlvyowxsgkzinc\n" +
                    "dwijheuxmkbstqpnvoza\n" +
                    "\n" +
                    "pnfbzdmysukvlj\n" +
                    "fzlksnydpjumvb\n" +
                    "djfmbqnvyzskplu\n" +
                    "\n" +
                    "ylxfuzsdr\n" +
                    "yxvfrzlkus\n" +
                    "yxlsfwrzu\n" +
                    "yulsfxzr\n" +
                    "yrzuxlfds\n" +
                    "\n" +
                    "cq\n" +
                    "qcp\n" +
                    "g\n" +
                    "\n" +
                    "hyadprtkis\n" +
                    "tykpiharsd\n" +
                    "sdyahrtpki\n" +
                    "pakifrhdyst\n" +
                    "ritysadhkp\n" +
                    "\n" +
                    "tdnuxmkhcveqgwasyr\n" +
                    "vmhctngxuawsrqykbed\n" +
                    "\n" +
                    "x\n" +
                    "dhkts\n" +
                    "pfg\n" +
                    "fg\n" +
                    "\n" +
                    "oz\n" +
                    "qnudf\n" +
                    "owzeg\n" +
                    "\n" +
                    "axkvulniypoezgdmcht\n" +
                    "kgeponhxactvylzdmi\n" +
                    "fdkotcgiwhnljbqmepazyrvx\n" +
                    "udhtkyexzncopglmvia\n" +
                    "olhadkzxiepngvytcm\n" +
                    "\n" +
                    "cxilwnkmdatosv\n" +
                    "saovmlncxiktwd\n" +
                    "swdmlnaivkotcx\n" +
                    "kdclnvtsiaoxwm\n" +
                    "vmndksiawtxolc\n" +
                    "\n" +
                    "pla\n" +
                    "ifgjtx\n" +
                    "\n" +
                    "zvfsaiykgrh\n" +
                    "vgzafikhsyr\n" +
                    "faghrvizsyk\n" +
                    "\n" +
                    "bvsldjymgzcqokie\n" +
                    "zstldyexgrwokvimjqb\n" +
                    "oqjgalksbymizcedv\n" +
                    "\n" +
                    "thkil\n" +
                    "puas\n" +
                    "vqhlt\n" +
                    "\n" +
                    "gvbhrqewyxj\n" +
                    "bgejxvh\n" +
                    "jsvibeagx\n" +
                    "geftjxbvhw\n" +
                    "exvgjbwh\n" +
                    "\n" +
                    "ywjaichxrfvq\n" +
                    "lnugcesm\n" +
                    "tcmoe\n" +
                    "etkbc\n" +
                    "\n" +
                    "vlitomya\n" +
                    "vmiplyoa\n" +
                    "amvliyo\n" +
                    "ayvlmio\n" +
                    "ovfdmajyli\n" +
                    "\n" +
                    "pxeqymbdt\n" +
                    "fetymxnzs\n" +
                    "\n" +
                    "ogerunlazpijskqfbmtdywv\n" +
                    "orgudspwmfzvyljniakqeb\n" +
                    "jkruynsdbcxifelogmpqvwza\n" +
                    "auprhvlodbwmqikgsjyezfn\n" +
                    "\n" +
                    "kjmehoatdxslfgrwyni\n" +
                    "dzrnowjumiveqaltpfkc\n" +
                    "jwmktnafrdieol\n" +
                    "\n" +
                    "z\n" +
                    "hu\n" +
                    "pd\n" +
                    "ap\n" +
                    "pjx\n" +
                    "\n" +
                    "hzjqrw\n" +
                    "qrzjah\n" +
                    "bvjizfyq\n" +
                    "\n" +
                    "wxpgcbzie\n" +
                    "ctegxwvh\n" +
                    "egxcqtwf\n" +
                    "\n" +
                    "zmwjpnviqde\n" +
                    "npgijdvhzmwq\n" +
                    "zwinjpqvmhd\n" +
                    "tmwzjdpiqnv\n" +
                    "\n" +
                    "thoezprianclgudvksyfbw\n" +
                    "gizdnfqwvebathopyurkl\n" +
                    "qeipwgrbvfndjtazhlokyu\n" +
                    "vodgpzryhxwtlenkfuiab\n" +
                    "tufkbyhegznadjilwvopr\n" +
                    "\n" +
                    "dbvigopmznrclaexjfwkyhtq\n" +
                    "kbvgmrioznjfycapxwleqdh\n" +
                    "zrqgpeasymbhokunvjxdilwcf\n" +
                    "\n" +
                    "ahmsunwpjzrtdlxqey\n" +
                    "mjuqrshdatxnpzelyw\n" +
                    "nrjqamdstpxlehwzuy\n" +
                    "qyxbahsrlmvzwuedjntp\n" +
                    "hudayszfmxptwljrqne\n" +
                    "\n" +
                    "zdanj\n" +
                    "manqwjed\n" +
                    "anzd\n" +
                    "jqdnwa\n" +
                    "fcaxdbn\n" +
                    "\n" +
                    "rabxt\n" +
                    "brta\n" +
                    "arbt\n" +
                    "tarb\n" +
                    "\n" +
                    "ajoshwczdmxkrivp\n" +
                    "fxpskmtchuzra\n" +
                    "pmyhacuzrxgkts\n" +
                    "bskzphxmcrael\n" +
                    "\n" +
                    "x\n" +
                    "x\n" +
                    "\n" +
                    "moay\n" +
                    "omay\n" +
                    "\n" +
                    "izocxhdkenqyavb\n" +
                    "ihlpsrnkfo\n" +
                    "twnpikho\n" +
                    "\n" +
                    "ftpahurnomkcvdzily\n" +
                    "ckapvofuzdlybtnrm\n" +
                    "neglmcpyrdzjavfutowk\n" +
                    "\n" +
                    "cdlnuqbvfejao\n" +
                    "vdsocqlfebxnau\n" +
                    "enjduqfcavblogm\n" +
                    "\n" +
                    "yfnhbem\n" +
                    "d\n" +
                    "j\n" +
                    "\n" +
                    "izhy\n" +
                    "ihyz\n" +
                    "zhyi\n" +
                    "ijzhy\n" +
                    "yhzi\n" +
                    "\n" +
                    "jxzchrsb\n" +
                    "xhi\n" +
                    "vegaxdn\n" +
                    "sfjopyx\n" +
                    "\n" +
                    "xu\n" +
                    "yxe\n" +
                    "x\n" +
                    "x\n" +
                    "x\n" +
                    "\n" +
                    "nyhlqrtzipagkmowuefvbcd\n" +
                    "ewhoialgqyfpmcnrdkzj\n" +
                    "roqhlinpdfwycmkgzase\n" +
                    "\n" +
                    "ytwerh\n" +
                    "utgwoirne\n" +
                    "wxsm\n" +
                    "\n" +
                    "xnjpohdmgykbtsraiqfu\n" +
                    "sjphqtbuoankirgxdymf\n" +
                    "amqpdilhfsytgoxbujknr\n" +
                    "fsxordjuayhgkpiqbmnt\n" +
                    "ipsvgmzyaqfdrtkuhonjbx\n" +
                    "\n" +
                    "xwekvftlbnujarm\n" +
                    "jweukmvanrbxltf\n" +
                    "luebtmwjranfkv\n" +
                    "jfuvklrbnmtwae\n" +
                    "rlhbvemkjfanwut\n" +
                    "\n" +
                    "pidycjeznrvh\n" +
                    "vcjbepznry\n" +
                    "wgnjvyofcaiplzer\n" +
                    "ermiyzpvjcnh\n" +
                    "pxrjqetknzvsyc\n" +
                    "\n" +
                    "qnxmivda\n" +
                    "xvdqim\n" +
                    "qvxdmi\n" +
                    "vxmqid\n" +
                    "vxdmqi\n" +
                    "\n" +
                    "wfapsg\n" +
                    "scwgdufr\n" +
                    "osfwg\n" +
                    "\n" +
                    "zfayobrc\n" +
                    "fyzobarc\n" +
                    "zobcryaf\n" +
                    "rfboycza\n" +
                    "\n" +
                    "musbrjnygkftpoxad\n" +
                    "sfnjgmoutkxrbyac\n" +
                    "nljabtukighmrqyxosf\n" +
                    "\n" +
                    "hwqxn\n" +
                    "wnhxq\n" +
                    "xbqhw\n" +
                    "\n" +
                    "vg\n" +
                    "qv\n" +
                    "v\n" +
                    "v\n" +
                    "qv\n" +
                    "\n" +
                    "lwo\n" +
                    "vwa\n" +
                    "wus\n" +
                    "\n" +
                    "iwecv\n" +
                    "dzvau\n" +
                    "\n" +
                    "ynewjdhtlcm\n" +
                    "npydwjmehlc\n" +
                    "\n" +
                    "l\n" +
                    "l\n" +
                    "l\n" +
                    "l\n" +
                    "l\n" +
                    "\n" +
                    "f\n" +
                    "m\n" +
                    "z\n" +
                    "\n" +
                    "gqbawtycdnzhfjvix\n" +
                    "wgnidzfxtajqychvb\n" +
                    "dfqzjwvanycxtighb\n" +
                    "ndgfatjwixvqhyczb\n" +
                    "\n" +
                    "lvsftm\n" +
                    "mtvlsf\n" +
                    "ltvsfm\n" +
                    "fvltsm\n" +
                    "tlsmvf\n" +
                    "\n" +
                    "wdvhntmbcausfgyk\n" +
                    "mcanyusbkvgftdw\n" +
                    "mauygksiwvftbcdn\n" +
                    "cftwojgesayvkmudbn\n" +
                    "kvdbcwafyzmnugsqt\n" +
                    "\n" +
                    "a\n" +
                    "bhngw\n" +
                    "a\n" +
                    "vu\n" +
                    "\n" +
                    "prxqlit\n" +
                    "pitqzr\n" +
                    "featyrpmsi\n" +
                    "iropt\n" +
                    "\n" +
                    "wkux\n" +
                    "txg\n" +
                    "\n" +
                    "dto\n" +
                    "o\n" +
                    "bj\n" +
                    "\n" +
                    "uagbxqkwit\n" +
                    "wvthxnqgaki\n" +
                    "hjqikngxaw\n" +
                    "odarkwgqpi\n" +
                    "wqagki\n" +
                    "\n" +
                    "atobwlprngejvmixdqcu\n" +
                    "ofwbtepxrqgimuyhdajkl\n" +
                    "\n" +
                    "hqeotif\n" +
                    "mpnvuyas\n" +
                    "\n" +
                    "qzdlxrp\n" +
                    "bdxzqrpl\n" +
                    "rhqzpldx\n" +
                    "qxpzrlbd\n" +
                    "\n" +
                    "wp\n" +
                    "pg\n" +
                    "dyvph\n" +
                    "wp\n" +
                    "pn\n" +
                    "\n" +
                    "netpfbl\n" +
                    "jario\n" +
                    "w\n" +
                    "\n" +
                    "pcefadnkhzv\n" +
                    "kgdhaupicxnezf\n" +
                    "\n" +
                    "eadohrcjnkgiypsmtlfvzuq\n" +
                    "hzaimfoqcuxtpdveykrgj\n" +
                    "aytcjiumfpkdvgrehozq\n" +
                    "btquhdlgfrmejkoiyvpzac\n" +
                    "qcvkdrywezfmtiujaoghp\n" +
                    "\n" +
                    "msueprdbjnzflgvytcwo\n" +
                    "glftyscmvbojzudwrpen\n" +
                    "jlgyfsntvwmrzdcuopbe\n" +
                    "osivwyfumczldjbgretqphn\n" +
                    "\n" +
                    "tuikjg\n" +
                    "nmibokj\n" +
                    "hbjikl\n" +
                    "\n" +
                    "bzgymjnd\n" +
                    "ndbygmzj\n" +
                    "yjnhbdmz\n" +
                    "jnyzbdm\n" +
                    "gibndyztmj\n" +
                    "\n" +
                    "iorhgcxbfjamwyenpvdksqu\n" +
                    "evytoqjxznkbadhrmisgfcw\n" +
                    "wbengjckvhmasfiyqrodx\n" +
                    "esdcnwxjohmqkrgiybfav\n" +
                    "ohkxbjgyvdeiqnsrcmawf\n" +
                    "\n" +
                    "mkqgwxicp\n" +
                    "qvailgsnxymo\n" +
                    "xqrmidg\n" +
                    "gqxihm\n" +
                    "xqmigrp\n" +
                    "\n" +
                    "zecksafgl\n" +
                    "jlazcgfek\n" +
                    "ugclqeakzxrf\n" +
                    "cgkoflzae\n" +
                    "eawcgkfzl\n" +
                    "\n" +
                    "lehtfqcx\n" +
                    "wojlmpdu\n" +
                    "\n" +
                    "bnsjyrcmah\n" +
                    "mynajrshbc\n" +
                    "nbrhscamyj\n" +
                    "jymhabnrsc\n" +
                    "cybjsrnamh\n" +
                    "\n" +
                    "uzybinv\n" +
                    "zvblpy\n" +
                    "xvlmybz\n" +
                    "\n" +
                    "aeuyibogwkxpvjt\n" +
                    "fismchnrzdqwp\n" +
                    "\n" +
                    "hgsnrqoupzitwafvxek\n" +
                    "hurvxiqezgknofaptws\n" +
                    "wagytrequfixhpvzonsk\n" +
                    "opknhiteqjwzxlfauvgrs\n" +
                    "\n" +
                    "rghduv\n" +
                    "aijsybl\n" +
                    "\n" +
                    "fboy\n" +
                    "body\n" +
                    "\n" +
                    "azhcqrk\n" +
                    "kmqfcuaz\n" +
                    "mickatzqhg\n" +
                    "qaosvkdzpcb\n" +
                    "cazkgwhtq\n" +
                    "\n" +
                    "snpgwemqclyd\n" +
                    "gfjhe\n" +
                    "rvgeubx\n" +
                    "jerkbigo\n" +
                    "oeigax\n" +
                    "\n" +
                    "lhsifzcg\n" +
                    "izhcfgls\n" +
                    "ishgzlcf\n" +
                    "\n" +
                    "msfqhtecuibyg\n" +
                    "gdwkvyiq\n" +
                    "yroxlivgqp\n" +
                    "\n" +
                    "wftdvlgcubj\n" +
                    "tsafjbwuiyxlqmr\n" +
                    "\n" +
                    "nsvibpqze\n" +
                    "y\n" +
                    "murd\n" +
                    "\n" +
                    "cbtukihfeqjrnv\n" +
                    "uchikvqtebr\n" +
                    "\n" +
                    "jgszxqvyfrakpl\n" +
                    "aslgzyfxpjvkrq\n" +
                    "sgyjaxzqvlfkpr\n" +
                    "yprgqvkxjsflza\n" +
                    "\n" +
                    "blxpv\n" +
                    "xvlqsp\n" +
                    "lvbxp\n" +
                    "\n" +
                    "bwu\n" +
                    "uwb\n" +
                    "\n" +
                    "kuctazm\n" +
                    "atcuzk\n" +
                    "tuqkczad\n" +
                    "cupkzta\n" +
                    "iupzckat\n" +
                    "\n" +
                    "virjwanfcxdsqkyzthmub\n" +
                    "shtdubncmkayzfqwjxri\n" +
                    "\n" +
                    "sdrvpcqybwomzah\n" +
                    "mvhskw\n" +
                    "swhemlv\n" +
                    "wmvsh\n" +
                    "hsmwlv\n" +
                    "\n" +
                    "wrivxopdhgfauslbe\n" +
                    "vnfeoxdwrmiqlyapcbsgu\n" +
                    "dolivuprewxazsbgf\n" +
                    "zudaxgosplbvfiwer\n" +
                    "oxiglrthpasvfwudeb\n" +
                    "\n" +
                    "gcjihxvtazydernl\n" +
                    "exdhjtgacvryu\n" +
                    "xqjhgystbrdaepcv\n" +
                    "dcfryegvmjaxthz\n" +
                    "\n" +
                    "n\n" +
                    "n\n" +
                    "yxna\n" +
                    "un\n" +
                    "\n" +
                    "uvsezitjwl\n" +
                    "midztxjcesgrw\n" +
                    "yulwizjset\n" +
                    "\n" +
                    "cpjn\n" +
                    "cjn\n" +
                    "ugnj\n" +
                    "njic\n" +
                    "jwn\n" +
                    "\n" +
                    "kmzjoe\n" +
                    "qhsvdg\n" +
                    "ta\n" +
                    "\n" +
                    "dtzar\n" +
                    "rtdz\n" +
                    "btzrd\n" +
                    "duzrt\n" +
                    "nkmszydrtxv\n" +
                    "\n" +
                    "rpjv\n" +
                    "oqvkyjp\n" +
                    "vemjp\n" +
                    "pjvm\n" +
                    "jtvp\n" +
                    "\n" +
                    "jqbywgpexdrc\n" +
                    "eihgzxtrknsl\n" +
                    "\n" +
                    "zukegspqxhridyf\n" +
                    "usfwpaihyjkxzerdq\n" +
                    "zyfriudebqxpshk\n" +
                    "\n" +
                    "nzsiehmplbjgfqw\n" +
                    "egwziblfhsqmjpn\n" +
                    "zslbnghpjfqiewm\n" +
                    "wgniseplhzfqbjm\n" +
                    "gaznqpwsembihlfj\n" +
                    "\n" +
                    "d\n" +
                    "knijh\n" +
                    "d\n" +
                    "xed\n" +
                    "lev\n" +
                    "\n" +
                    "cfzpjatlw\n" +
                    "taclzpjwf\n" +
                    "cltjfzpaw\n" +
                    "fptzjclaw\n" +
                    "tfcpwlzsaj\n" +
                    "\n" +
                    "ni\n" +
                    "ind\n" +
                    "\n" +
                    "jnpydc\n" +
                    "dynjpc\n" +
                    "jpcynd\n" +
                    "ncdjyp\n" +
                    "\n" +
                    "wuilxjabeftcro\n" +
                    "shpkudnygvmrq\n" +
                    "\n" +
                    "yqzhalsjf\n" +
                    "azutsmkq\n" +
                    "qaszr\n" +
                    "qmrzsxa\n" +
                    "\n" +
                    "wjv\n" +
                    "wxjv\n" +
                    "wjv\n" +
                    "wjv\n" +
                    "\n" +
                    "esgpbow\n" +
                    "epogwbs\n" +
                    "oewpsbg\n" +
                    "wpgqmscobe\n" +
                    "ewsobpg\n" +
                    "\n" +
                    "b\n" +
                    "b\n" +
                    "bw\n" +
                    "\n" +
                    "rgz\n" +
                    "jvrgpa\n" +
                    "tzrgk\n" +
                    "rtegf\n" +
                    "rxgk\n" +
                    "\n" +
                    "bcotpdrwmu\n" +
                    "dwkmpbtcur\n" +
                    "\n" +
                    "rdzyjbvsmuoacwkg\n" +
                    "fhciwsnzamkugpdybrvox\n" +
                    "\n" +
                    "mwpgv\n" +
                    "zvw\n" +
                    "\n" +
                    "wbyktilsjuemvqpdornczhx\n" +
                    "kyfzbqitgahrvsuocjpledmn\n" +
                    "qhytnurliebszcdvmpojk\n" +
                    "\n" +
                    "ohxsjvdzqabegp\n" +
                    "oqvgxrjbtelpuw\n" +
                    "gqevkbpjnxoi\n" +
                    "\n" +
                    "fcjsuviaq\n" +
                    "asvcfjuiq\n" +
                    "aqcfsujiv\n" +
                    "sicfaqjvu\n" +
                    "vaiqusfcj\n" +
                    "\n" +
                    "icjtklarqhsmdy\n" +
                    "qcamftiujys\n" +
                    "zibcntjyasgoxeqm\n" +
                    "wvyitlamrqsujpc\n" +
                    "\n" +
                    "hnmxwtudcsbp\n" +
                    "ryzdijaguqvfko\n" +
                    "\n" +
                    "twqousdgyknvrmx\n" +
                    "fpijbzeh\n" +
                    "\n" +
                    "ixg\n" +
                    "mxiv\n" +
                    "xi\n" +
                    "\n" +
                    "w\n" +
                    "wu\n" +
                    "w\n" +
                    "gw\n" +
                    "\n" +
                    "e\n" +
                    "e\n" +
                    "\n" +
                    "nktazsgmqvp\n" +
                    "kxtcvsaznmpg\n" +
                    "\n" +
                    "xm\n" +
                    "k\n" +
                    "m\n" +
                    "mx\n" +
                    "\n" +
                    "ntfkyoarlejixbd\n" +
                    "colnibtxeryjadfk\n" +
                    "yagxfwbisvhurjmpkqt\n" +
                    "\n" +
                    "jfqhmekxduwari\n" +
                    "xhwfrdmqjuiake\n" +
                    "lajdxeuikmhrqfw\n" +
                    "ihdkmeafjqwurx\n" +
                    "\n" +
                    "otjeuvbqshdncxa\n" +
                    "pmlcvukgsexriyabhq\n" +
                    "bnvxquaeodtwcshf\n" +
                    "\n" +
                    "fgeu\n" +
                    "oec\n" +
                    "\n" +
                    "mjflpw\n" +
                    "jlwfpim\n" +
                    "fwmlqpj\n" +
                    "jpfmwlk\n" +
                    "\n" +
                    "vpjcbfaihnusglr\n" +
                    "rbvpcsfyihnjazguxl\n" +
                    "\n" +
                    "kq\n" +
                    "k\n" +
                    "k\n" +
                    "\n" +
                    "pign\n" +
                    "pkgh\n" +
                    "ajp\n" +
                    "pq\n" +
                    "pzomcb\n" +
                    "\n" +
                    "qbo\n" +
                    "hstryu\n" +
                    "fljioe\n" +
                    "\n" +
                    "nypszgxrdhbe\n" +
                    "rxeyhpnsdzgb\n" +
                    "epghbynszrxd\n" +
                    "\n" +
                    "azlbegicyv\n" +
                    "iavnezslg\n" +
                    "\n" +
                    "ymtkef\n" +
                    "oasrun\n" +
                    "wvzl\n" +
                    "uerpw\n" +
                    "qcidxbhgj\n" +
                    "\n" +
                    "hxqgt\n" +
                    "gthqx\n" +
                    "\n" +
                    "pocvsz\n" +
                    "otkwzpvs\n" +
                    "zvosp\n" +
                    "vopcnzsl\n" +
                    "vzmpnfos\n" +
                    "\n" +
                    "rz\n" +
                    "zgr\n" +
                    "hrvze\n" +
                    "rsz\n" +
                    "\n" +
                    "uebwmzk\n" +
                    "purbtkdm\n" +
                    "eyumskvjib\n" +
                    "\n" +
                    "d\n" +
                    "d\n" +
                    "d\n" +
                    "nd\n" +
                    "\n" +
                    "kdarcnph\n" +
                    "kouwr\n" +
                    "tuexkor\n" +
                    "\n" +
                    "hnslcrtwyudpbxgv\n" +
                    "htsrvqelyagudwbpo\n" +
                    "mtubsahrkvpeyqwdlgf\n" +
                    "\n" +
                    "r\n" +
                    "r\n" +
                    "r\n" +
                    "r\n" +
                    "r\n" +
                    "\n" +
                    "xptijvhfa\n" +
                    "xpricabvtfhj\n" +
                    "vjpaxfhti\n" +
                    "ahtxfvjpi\n" +
                    "vhftijpxa\n" +
                    "\n" +
                    "bxshqfzgyr\n" +
                    "bzgfxsrqyh\n" +
                    "szrqhgfxby\n" +
                    "txbczyhfqsrg\n" +
                    "ybfhsqzxrg\n" +
                    "\n" +
                    "taevdznpkf\n" +
                    "ezadwvfnkplt\n" +
                    "kdpnzafvte\n" +
                    "tvfdknpeaz\n" +
                    "\n" +
                    "ea\n" +
                    "a\n" +
                    "a\n" +
                    "a\n" +
                    "a\n" +
                    "\n" +
                    "dzwyofjxnugvbipar\n" +
                    "uwrfvygonibzadxjp\n" +
                    "\n" +
                    "afcm\n" +
                    "cmaf\n" +
                    "facm\n" +
                    "\n" +
                    "lcisgd\n" +
                    "jbkcid\n" +
                    "\n" +
                    "y\n" +
                    "y\n" +
                    "djgyen\n" +
                    "yl\n" +
                    "\n" +
                    "tfbvzwocks\n" +
                    "bzfstkvjcoy\n" +
                    "kzuvsobxficthn\n" +
                    "kftzogvcbs\n" +
                    "vszjkobtfygc\n" +
                    "\n" +
                    "heszp\n" +
                    "uhzepx\n" +
                    "zehp\n" +
                    "shepz\n" +
                    "\n" +
                    "b\n" +
                    "ymel\n" +
                    "z\n" +
                    "zhq\n" +
                    "s\n" +
                    "\n" +
                    "wvhlzgcet\n" +
                    "bkuwzeopm\n" +
                    "nbjwfaeqmkz\n" +
                    "\n" +
                    "mqaufjvwl\n" +
                    "qlfuvirnjw\n" +
                    "yvuwfglxejzt\n" +
                    "\n" +
                    "gkylzr\n" +
                    "lwdiykg\n" +
                    "\n" +
                    "zuloiwargvxk\n" +
                    "evxcy\n" +
                    "\n" +
                    "gjrvnwbxu\n" +
                    "bvpugixnwj\n" +
                    "uwrmjvngbx\n" +
                    "gcnvwbxuj\n" +
                    "jwnuxbvg\n" +
                    "\n" +
                    "q\n" +
                    "q\n" +
                    "q\n" +
                    "q\n" +
                    "ewq\n" +
                    "\n" +
                    "zwynrv\n" +
                    "uvxym";

    private static final String[] INPUT_AS_GROUP_ARRAY = INPUT.split("\\R\\R+");

    public static class Group {
        final Set<Character> questionsAnyone;
        final Set<Character> questionsEveryone;

        public Group(Set<Character> questionsAnyone, Set<Character> questionsEveryone) {
            this.questionsAnyone = questionsAnyone;
            this.questionsEveryone = questionsEveryone;
        }

        public static Group fromString(String entry) {
            Set<Character> questionsAnyone = new HashSet<>();
            Set<Character> questionsEveryone = new HashSet<>();

            for (char c : entry.toCharArray()) {
                if (((Character) c).toString().matches("[a-z]")) {
                    questionsAnyone.add(c);
                }
            }

            String[] inputLines = entry.split("\\R");
            int index = 0;

            for (String line : inputLines) {
                if (index == 0) {
                    for (char c : line.toCharArray()) {
                        // Add all at first
                        if (((Character) c).toString().matches("[a-z]")) {
                            questionsEveryone.add(c);
                        }
                    }
                } else {
                    questionsEveryone.removeIf(c -> !line.matches(".*" + c + ".*"));
                }
                index++;
            }
            return new Group(questionsAnyone, questionsEveryone);
        }

        public int getNrQuestionsAnyone() {
            return questionsAnyone.size();
        }

        public int getNrQuestionsEveryone() {
            return questionsEveryone.size();
        }
    }

    public static long doPuzzle1() {
        int sum = 0;
        for (String groupString : INPUT_AS_GROUP_ARRAY) {
            Group group = Group.fromString(groupString);
            sum += group.getNrQuestionsAnyone();
        }
        return sum;
    }

    public static long doPuzzle2() {
        int sum = 0;
        for (String groupString : INPUT_AS_GROUP_ARRAY) {
            Group group = Group.fromString(groupString);
            sum += group.getNrQuestionsEveryone();
        }
        return sum;
    }
}
