package com.github.rviehmann.aoc2022;

public class Day02 {

    // From: https://adventofcode.com/2022/day/2/input
    private static final String INPUT =
            "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "C X\n" +
                    "C X\n" +
                    "A Z\n" +
                    "B X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "B X\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "B Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A X\n" +
                    "C X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "A X\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A X\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C X\n" +
                    "A X\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A X\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C X\n" +
                    "A X\n" +
                    "B Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "A X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C X\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A X\n" +
                    "C Y\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "A X\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C X\n" +
                    "A X\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "B X\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "B Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "C X\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "A X\n" +
                    "A X\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "A X\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "C X\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "A X\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B X\n" +
                    "A X\n" +
                    "B Z\n" +
                    "A X\n" +
                    "B Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "B Z\n" +
                    "C X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A X\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B X\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "A X\n" +
                    "B Y\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A X\n" +
                    "C X\n" +
                    "A X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A X\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A X\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "A X\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C X\n" +
                    "A X\n" +
                    "B X\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "B X\n" +
                    "A X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "B Y\n" +
                    "A X\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "A X\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Z\n" +
                    "A X\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "C X\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "B X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Y\n" +
                    "A X\n" +
                    "B Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "B Y\n" +
                    "B X\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "B X\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "A X\n" +
                    "C Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C X\n" +
                    "A X\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "A X\n" +
                    "B Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "A X\n" +
                    "C X\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C X\n" +
                    "A X\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A X\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C X\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "A X\n" +
                    "C X\n" +
                    "B Y\n" +
                    "B X\n" +
                    "A X\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A X\n" +
                    "C Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "B X\n" +
                    "B Z\n" +
                    "C X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C X\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C X\n" +
                    "B X\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "B X\n" +
                    "A X\n" +
                    "A X\n" +
                    "A X\n" +
                    "C X\n" +
                    "B X\n" +
                    "C Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "A X\n" +
                    "C X\n" +
                    "C Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "B X\n" +
                    "A X\n" +
                    "A X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C X\n" +
                    "B Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "B X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C X\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A X\n" +
                    "B X\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C X\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C X\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A X\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "C X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A X\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "B X\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "C X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Z\n" +
                    "C X\n" +
                    "C X\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Y\n" +
                    "B X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A X\n" +
                    "C Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "B Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C X\n" +
                    "A X\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C X\n" +
                    "A X\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C X\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "B Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Z\n" +
                    "A X\n" +
                    "B Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "A Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "A X\n" +
                    "B Y\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "C X\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "B Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "C Z\n" +
                    "C Y\n" +
                    "B Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "A Z\n" +
                    "C X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "C X\n" +
                    "B Y\n" +
                    "B X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "B Z\n" +
                    "A X\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "B Y\n" +
                    "C Z\n" +
                    "C X\n" +
                    "C X\n" +
                    "B X\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "A X\n" +
                    "A Z\n" +
                    "A X\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "B Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "C X\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "B Z\n" +
                    "A X\n" +
                    "A X\n" +
                    "B Y\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Z\n" +
                    "A Y\n" +
                    "B X\n" +
                    "A Y\n" +
                    "A Y\n" +
                    "A X\n" +
                    "A X\n" +
                    "C Z\n" +
                    "B Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Y\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "B X\n" +
                    "C Z\n" +
                    "C Z\n" +
                    "C X\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n" +
                    "C Z\n" +
                    "A Y\n";

    private static final String[] INPUT_AS_LINE_ARRAY = INPUT.split("\\R");
    private static final long scoreForWin = 6;
    private static final long scoreForDraw = 3;
    private static final long scoreForLose = 0;

    private static long calculateScoreForRound(String round) {
        // The first column is what your opponent is going to play: A for Rock, B for Paper, and C for Scissors.
        // The second column, you reason, must be what you should play in response: X for Rock, Y for Paper, and Z for Scissors.
        // The score for a single round is the score for the shape you selected (1 for Rock, 2 for Paper, and 3 for Scissors)
        // plus the score for the outcome of the round (0 if you lost, 3 if the round was a draw, and 6 if you won).
        long scoreForShape = round.toCharArray()[2] - 'X' + 1;
        long scoreForOutcome = calculateScoreForOutcome(round);

        // System.out.println("Round: " + round + " yields scoreForShape: " + scoreForShape + ", scoreForOutcome: " + scoreForOutcome);

        return scoreForShape + scoreForOutcome;
    }

    private static long calculateScoreForOutcome(String round) {
        switch (round) {
            case "A X": /*Same*/
                return scoreForDraw;
            case "A Y": /*Opponent: Rock, me: Paper*/
                return scoreForWin;
            case "A Z": /*Opponent: Rock, me: Scissors*/
                return scoreForLose;

            case "B X": /*Opponent: Paper, me: Rock*/
                return scoreForLose;
            case "B Y": /*Same*/
                return scoreForDraw;
            case "B Z": /*Opponent: Paper, me: Scissors*/
                return scoreForWin;

            case "C X": /*Opponent: Scissors, me: Rock*/
                return scoreForWin;
            case "C Y": /*Opponent: Scissors, me: Paper*/
                return scoreForLose;
            case "C Z": /*Same*/
                return scoreForDraw;

            default:
                throw new IllegalArgumentException("Invalid round: " + round);
        }
    }

    public static long doPuzzle1() {
        long sum = 0;
        for (String round : INPUT_AS_LINE_ARRAY) {
            sum += calculateScoreForRound(round);
        }
        return sum;
    }

    public static long doPuzzle2() {
        //TODO
        return 0;
    }
}
